### ISSUE TITLE
Writing data during dtor fails

### ISSUE THREAD

**Issue by olafx** [h5py/h5py#2007] opened 2021-11-24 11:25 UTC
I have this class where I write some data during its destructor, which is only called when the entire program starts shutting down. This doesn't work apparently, and I think this is a bug.

```
Exception ignored in: <function N_Body_h5.__del__ at 0x103c6f940>
Traceback (most recent call last):
  File "/Users/swift/Dev/gravity0/ic_gen/n_body_h5.py", line 89, in __del__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "/Users/swift/venv/main/lib/python3.9/site-packages/h5py/_hl/group.py", line 305, in __getitem__
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open
  File "h5py/h5i.pyx", line 46, in h5py.h5i.wrap_identifier
ImportError: sys.meta_path is None, Python is likely shutting down
```

```Python
import h5py
import numpy as np

class N_Body_h5:
    def __init__(self, name: str, n_times: int = 1, time_group_size: int = 16384, time_chunk_size: int = 256):
        self.fp              = h5py.File(name + '.h5', 'w', libver='latest')
        self.time_count      = 0
        self.n_times         = n_times
        self.times           = np.empty([min(n_times, time_group_size)], dtype=np.float64)
        self.time_group_size = time_group_size
        self.time_chunk_size = time_chunk_size
        self.n_prev          = None
        self.had_vel_prev    = None
        self.fp.attrs.create('time chunk size', time_group_size, dtype=np.uint32)
    def write(self, positions: np.ndarray, velocities: np.ndarray = None, time: float = 0):
        if velocities is not None:
            if positions.shape != velocities.shape:
                raise BufferError('positions and velocities should have the same shape')
        n = positions.shape[0]
        if self.n_prev is not None and self.n_prev != n:
            raise BufferError("number of objects can't be changing throughout the initial condition")
        if self.had_vel_prev and velocities is None:
            raise BufferError('either all or none of the times must have velocities')
        if self.time_count % self.time_group_size == 0:
            #   Save times.
            if self.time_count != 0:
                self.fp['/' + str(self.time_count // self.time_group_size - 1)].create_dataset('times', data=self.times)
            #   Time for a new group.
            group = self.fp.create_group(str(self.time_count // self.time_group_size))
            group.create_dataset('pos', shape=(0, n, 3), maxshape=(None, n, 3),
                                 chunks=(self.time_chunk_size, n, 3), dtype=np.float64, compression='szip')
            if velocities is not None:
                group.create_dataset('vel', shape=(0, n, 3), maxshape=(None, n, 3),
                                     chunks=(self.time_chunk_size, n, 3), dtype=np.float64, compression='szip')
        else:
            group = self.fp['/' + str(self.time_count // self.time_group_size)]
        self.times[self.time_count % self.time_group_size] = time
        group['pos'].resize(self.time_count % self.time_group_size + 1, axis=0)
        if velocities is not None:
            group['vel'].resize(self.time_count % self.time_group_size + 1, axis=0)
        group['pos'][self.time_count % self.time_group_size] = positions
        if velocities is not None:
            group['vel'][self.time_count % self.time_group_size] = velocities
        self.n_prev = n
        self.had_vel_prev = velocities is not None
        self.time_count += 1

    def __del__(self):
        self.fp['/' + str(self.time_count // self.time_group_size)].create_dataset('times', data=self.times[:(self.time_count % self.time_group_size)])
        self.fp.close()

if __name__ == '__main__':
    generator = np.random.default_rng(0)
    n         = 16
    #   Test without velocities and one time.
    writer    = N_Body_h5('0')
    positions = generator.normal(0, 1, (n, 3))
    writer.write(positions)
    #   Test with velocities over multiple times.
    n_times   = 7
    times     = np.linspace(0, 1, n_times)
    writer    = N_Body_h5('1', n_times, 5)
    for time in times:
        positions  = generator.normal(0, 1, (n, 3))
        velocities = generator.normal(0, 1, (n, 3))
        writer.write(positions, velocities, time)

```

The code looks something like this. Is pretty complicated, but the main idea is that the destructor creates a new dataset, and this fails for seemingly no reason except that the destructor is called while Python is closing.

macOS Monterey
Python 3.9.8
h5py 3.5.0
HDF5 1.12

**Comment by aragilar** [comment] 2021-11-24 11:53
I'm not sure why the `meta_path` is empty, but I suspect the issue is the conditional imports in `wrap_identifier`, which may be there to avoid circular imports (as a first guess).

**Comment by takluyver** [comment] 2021-11-24 12:00
Destructors are already kind of a weird environment (there's no caller, so nowhere for errors to be propagated), and code that runs when Python is shutting down is also in a weird state. So it's best not to rely on this kind of thing.

Instead, you could do something like:

- Use a `try` / `finally` block and write out the data that you want in the `finally` bit.
- Give your class `__enter__` and `__exit__` methods, with `__exit__` writing the data, and use it as a `with N_Body_h5(...) as writer:` block.
- Use the [atexit](https://docs.python.org/3/library/atexit.html) module to run something when Python shuts down. If I recall correctly, functions registered with this are called *before* the interpreter really shuts down, so things like this can still work.

**Comment by olafx** [comment] 2021-11-24 13:05
> 

Thanks, these are nicer solutions than what I used.

**Comment by takluyver** [comment] 2021-12-01 09:10
I'm going to close this because, from my perspective, the best fixes are to restructure code to not do significant work in `__del__` methods, and especially in `__del__` methods on global objects (which will only be called at interpreter shutdown). There might be changes in h5py that would make it work *better* in this situation, but it still wouldn't be the best way to use it, and any changes may have a cost in complexity or performance. So I'd rather just point people to a better option.

**Closed by takluyver** 2021-12-01 09:10 UTC
