### ISSUE TITLE
Unable to use basic swmr functionality

### ISSUE THREAD

**Issue by arpit15** [h5py/h5py#824] opened 2017-01-13 19:57 UTC
I am trying to read a file while another process is writing it.
I am using 
h5py version 2.6.0
ubuntu 14.04
When I open the file using `f = h5py.File(filename, 'r', libver='latest', swmr=True)`
I get following error
ValueError: The SWMR feature is not available in this version of the HDF5 library

Kindly let me in which version is swmr fully functional.
Thank you

**Comment by tacaswell** [comment] 2017-01-13 21:45
You need hdf5  1.10, you likely have 1.8.

**Comment by arpit15** [comment] 2017-01-14 22:36
thank you. I had 1.8.11. I installed hdf5 version 1.10 from source. Then I reinstalled h5py using pip. Still it is not able to recognize hdf5 1.10 version. I will try more and post detailed steps for someone facing the same problem.

**Comment by tacaswell** [comment] 2017-01-15 04:57
I am going to close this as not a bug.

Could you add your notes as a pull request to expand https://github.com/h5py/h5py/blob/ed091b956f739cb571eb8b2a73c967b45e930b90/docs/swmr.rst ?

**Closed by tacaswell** 2017-01-15 04:57 UTC

**Comment by alfonnews** [comment] 2017-11-09 17:53
@arpit15 I had the same problem. I installed version 1.10 following this instruccions but this don't work.
https://gist.github.com/episodeyang/dfa69365203639fcde5f2aae73f7d9ac

**Comment by tacaswell** [comment] 2017-11-14 02:58
@alfonnews Please open a new issue for this.

**Comment by mike-lawrence** [comment] 2018-02-07 14:48
I encountered something similar, ended up deleting /usr/local, reinstalling hdf5 1.10.1_2 & python via  brew (I'm on OS X), only to find that installing h5py from pip and then from source both thought they were using hdf5 1.8. I finally got it to work and I *think* that installing via `pip2 install h5py --verbose --no-cache-dir --no-binary :all:` was the trick.
