### ISSUE TITLE
h5py 3.6 fails to import

### ISSUE THREAD

**Issue by khamyl** [h5py/h5py#2037] opened 2022-01-13 08:26 UTC
* __Operating System:__ Windows 10
 * __Python version:__ 3.9.7
 * __Where Python was acquired:__ Miniconda on Windows
 * __h5py version:__ 3.6.0
 * __HDF5 version:__ 1.10.6
 * The full traceback/stack trace shown:

```
(tf-gpu) d:\WS\Python>python
Python 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\Miniconda3\envs\tf-gpu\lib\site-packages\h5py\__init__.py", line 33, in <module>
    from . import version
  File "C:\Users\...\Miniconda3\envs\tf-gpu\lib\site-packages\h5py\version.py", line 15, in <module>
    from . import h5 as _h5
  File "h5py\h5.pyx", line 1, in init h5py.h5
ImportError: DLL load failed while importing defs: The specified procedure could not be found.
>>> 
```

**Comment by takluyver** [comment] 2022-01-13 11:42
You say 'h5py 2.8' in the title, but in the description you say it's version 3.6?

That error looks like there's a mismatch between the version of HDF5 you're using and the version used to build h5py. That suggests that whoever made the conda package didn't specify the relationship tightly enough. If you're using conda-forge, there's an issue here: https://github.com/conda-forge/h5py-feedstock/issues/103 . If you're getting h5py from the default channel maintained by Anaconda, you could try reporting an issue at https://github.com/ContinuumIO/anaconda-issues/issues .

**Comment by khamyl** [comment] 2022-01-13 12:49
Reported here: https://github.com/conda/conda/issues/11142

**Comment by takluyver** [comment] 2022-01-13 12:51
Thanks. I'll close this one, because I think this is an issue with the conda packaging of h5py, not a bug in h5py itself.

**Closed by takluyver** 2022-01-13 12:51 UTC
