### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by ghisvail** [h5py/h5py#669] opened 2016-01-24 11:23 UTC
The last tagged release is from **April 2015** and it seems that quite a few bugfixes and enhancements have landed in the codebase since. The next Ubuntu LTS is around the corner and import from Debian will be frozen very soon, so now would be a great time to update the packaging with a new release, if considered.

Cheers,

**Comment by andrewcollette** [comment] 2016-01-26 14:37
I agree... I simply haven't had time recently.  Will try to get to it this week.

**Comment by ghisvail** [comment] 2016-01-27 09:40
No problem. Thanks for considering it. I will update the packaging as soon as the new release is tagged. Cheers.

**Comment by andrewcollette** [comment] 2016-02-02 05:31
2.6.0 is tagged.

**Comment by pope1ni** [comment] 2016-02-08 09:35
@andrewcollette - a few issues regarding the release:
- Would it be possible to upload the 2.6 release to PyPI now that it has been tagged?
- The ANN.rst document needs to be updated for the 2.6 release.
- The _what's new?_ pages appear to be missing for 2.5 and 2.6 releases.

Would it be possible to have these issues addressed?

**Comment by ghisvail** [comment] 2016-02-08 09:42
FYI, the Debian packaging has been successfully updated with version `2.6.0`. It should normally transition to the next release of Ubuntu. You guys may decide to address the points raised by @pope1ni, but please consider doing so in a point release to minimize the difference between the tagged and PyPI tarballs. Cheers.

**Comment by andrewcollette** [comment] 2016-02-10 03:08
Yes, I think we will do a 2.6.1 as the initial public release, once we have time to get these bits up to date.

**Comment by jakirkham** [comment] 2016-02-17 04:51
Would it make sense to do a 2.6.0 release on PyPI now or would it be better to wait for these changes and do a 2.6.1 release on PyPI once completed?

**Comment by aragilar** [comment] 2017-02-20 07:34
This is effectively a duplicate of #784, closing this in place of #784.

**Closed by aragilar** 2017-02-20 07:34 UTC
