### ISSUE TITLE
annoying float to double conversion warning

### ISSUE THREAD

**Issue by gaming-hacker** [h5py/h5py#983] opened 2018-01-19 19:40 UTC
hello,
i ran 
python -c 'import h5py; print(h5py.version.info)'.

/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  2.7.14 (default, Sep 22 2017, 00:06:07) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.14.0

**Comment by aragilar** [comment] 2018-01-20 00:54
Duplicate of #961.

**Closed by aragilar** 2018-01-20 00:54 UTC
Labels: duplicate

**Comment by gaming-hacker** [comment] 2018-01-20 14:25
in my fork, i pulled
pr979 and warning is still there
