### ISSUE TITLE
Virtual datasets are not resizable

### ISSUE THREAD

**Issue by 1313e** [h5py/h5py#1490] opened 2020-02-04 04:53 UTC
To assist reproducing bugs, please include the following:
h5py    2.10.0
HDF5    1.10.4
Python  3.7.4 (default, Aug 13 2019, 20:35:49) 
[GCC 7.3.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.17.2

I am not sure if this is the way it is supposed to work, but according to the documentation ([here](http://docs.h5py.org/en/stable/vds.html#VirtualLayout)), virtual datasets should be resizable if their layouts are created with a `maxshape` bigger than their current shape.

So, if I am not mistaken, the following should work (assuming that `test0.hdf5` exists of course):
```python
import h5py
with h5py.File('test.hdf5', 'w') as file:
    layout = h5py.VirtualLayout(shape=(1,), dtype=float, maxshape=(None,))
    layout[0] = h5py.VirtualSource('test0.hdf5', 'data', shape=(1,), dtype=float)
    dset = file.create_virtual_dataset('test', layout)
    dset.resize(2, axis=0)
```
However, this will raise the following error: `TypeError: Only chunked datasets can be resized`.

If I take a look at `dset`, it does correctly report a maximum shape of `(None,)`, but (as stated by the error), `dset.chunks` returns `None`.
As the layout itself does not have a `resize()`-method, I cannot resize the virtual dataset that way either.

So, how does this work?
Are virtual datasets supposed to be resizable and I am doing something wrong, or can they simply not be resized and the documentation is wrong/outdated?

**Comment by takluyver** [comment] 2020-02-07 10:30
HDF5 allows for resizing virtual datasets, but as far as I know it only makes sense where you've mapped in a source with an unlimited dimension, which concept h5py doesn't currently expose (see #1202).

My take is that virtual datasets should always be cheap to create, so I don't feel much pressure to work on ways to modify them after creation: just delete and recreate them when you need something different.

I'll close this issue as I think it's a duplicate of #1167.

**Closed by takluyver** 2020-02-07 10:30 UTC
