### ISSUE TITLE
[BUG] read_direct() does not take shape of array into account

### ISSUE THREAD

**Issue by jmd-dk** [h5py/h5py#1773] opened 2020-12-02 15:36 UTC
### Short description
The `read_direct()` method on datasets does not always take the shape of the preexisting array into account, but only the shape of the dataset itself. Indeed, looking at the `select()` function in `h5py/_hl/selections.py`, the `shape` argument is never used in the case of both `len(args) != 1` and `dataset is not None`. Thus code where we read into a sliced array is broken, e.g.
```python
with h5py.File(myfile, mode='r') as f:
    f['data'].read_direct(arr, dest_sel=np.s_[:, :size])
```
where `arr` is a preexisting 2D array, with `arr.shape[1] > size`.

### Cause
This problem is not there in version 2.10.0, but appears in 3.0.0 and remains in 3.1.0. I believe the bug is introduced in #1526, specifically 474ef53d2698f6fa8988df2a2ec99525863bc8c4, where (some of) the changes to `h5py/_hl/selections.py` are
```python
-    sel = SimpleSelection(shape)	
-    sel[args]
-    return sel
---
+    if dataset is not None:
+        selector = dataset._selector
+    else:
+        space = h5s.create_simple(shape)
+        selector = _selector.Selector(space)
+    return selector.make_selection(args)
```
Note that in the new code, `shape` is completely neglected if `dataset is not None`.

### Complete example
The code below does the following:

 A) Generate an array of shape `(2, 2)` and write it to disk.
 B) Read the array back in using `[...]`.
 C) Read the array back in using `read_direct()` into an array of matching shape.
 D) Read the array back in using `read_direct()` into a slightly too large array, with properly specified `dest_sel` argument to `read_direct()`.

```python
import numpy as np
import h5py

# Generate data
size = 2
shape = (size, size)
data = np.zeros(shape, dtype=np.double)
count = 0
for i in range(size):
    for j in range(size):
        data[i, j] = count
        count += 1
print('A:', data)

# Write data
with h5py.File('data.hdf5', mode='w') as f:
    dset = f.create_dataset('data', shape, dtype=np.double)
    dset[...] = data

# Read data
with h5py.File('data.hdf5', mode='r') as f:
    data_read = f['data'][...]
print('B:', data_read)

# Read data using read_direct
data_read_direct = -np.ones(shape, dtype=np.double)
with h5py.File('data.hdf5', mode='r') as f:
    f['data'].read_direct(
        data_read_direct,
        dest_sel=np.s_[:, :size],  # does not matter
    )
print('C:', data_read_direct)

# Read data using read_direct into larger array
shape_large = (size, size + 1)
data_read_direct_large = -np.ones(shape_large, dtype=np.double)
with h5py.File('data.hdf5', mode='r') as f:
    f['data'].read_direct(
        data_read_direct_large,
        dest_sel=np.s_[:, :size],  # should matter!
    )
data_read_direct_large_sliced = data_read_direct_large[:, :size]
print('D:', data_read_direct_large_sliced)
```

At each stage the result is printed. We get

> A: [[0. 1.]
 [2. 3.]]
B: [[0. 1.]
 [2. 3.]]
C: [[0. 1.]
 [2. 3.]]
D: [[ 0.  1.]
 [ 3. -1.]]

We see that D fails, with the read effectively being carried out into `data_read_direct_large[...]` rather than `data_read_direct_large[:, :size]`, despite supplying `dest_sel=np.s_[:, :size]`. I believe the problem only occurs when the slice of the array in which to read in the data (well *write the data to*, but from disk to memory) is non-contiguous, which is the case for most slices of multi-dimensional arrays. I stress that this non-contiguousity should be perfectly OK (and used to be), as long as it's encoded by `dest_sel` and the array itself *is* contiguous.

It's not true that the argument `dest_sel` is completely ignored, as leaving it out on D results in

> TypeError: Can't broadcast (2, 2) -> (2, 3)

(which is fair), though setting it correctly does not result in the expected behavior.

### Fix
I'm not well-versed on the h5py internals, so I won't suggest a proper fix, though obviously the `shape` argument to `_hl.selections.select()` must not go unused. For the simple example above, removing
```python
selector = dataset._selector
```
and always going with
```python
space = h5s.create_simple(shape)
selector = _selector.Selector(space)
```
does in fact work, but I don't know if this causes other use cases to break.

Interestingly, `read_direct()` is being tested in `tests/test_dataset.py`, but it appears that only 1D arrays are tried, whereas this problem is inherent to multi-dimensional arrays.

I guess it's worth also checking up on `write_direct()`.

### System specifications
 * OS: CentOS Linux 7, Linux Mint 19.3
 * Python: 3.9 (build from source)
 * h5py: 3.0.0rc1, 3.0.0, 3.1.0
 * HDF5: 1.10.6, 1.12.0
 * NumPy: 1.19.4
 * Cython: 0.29.21

**Comment by theacetoace** [comment] 2020-12-14 11:20
Same problem, fixed for myself when changed

```python
if dest_sel is None:
    dest_sel = sel.SimpleSelection(dest.shape)
else:
   dest_sel = sel.select(dest.shape, dest_sel, self)
```

to 

```python
if dest_sel is None:
    dest_sel = sel.SimpleSelection(dest.shape)
else:
   dest_sel = sel.select(dest.shape, dest_sel)
```

in **read_direct** method of dataset.

**Comment by bmerry** [comment] 2021-01-13 13:35
@jmd-dk I'm seeing a possibly related problem where if I use just `:` as a destination slice I get a segmentation fault, but if I explicitly specify 0:size (where "size" is the size of the destination array on that axis) then it is fine. Does that sound like it's caused by the same underlying bug?

**Comment by jmd-dk** [comment] 2021-01-13 15:45
> @jmd-dk I'm seeing a possibly related problem where if I use just `:` as a destination slice I get a segmentation fault, but if I explicitly specify 0:size (where "size" is the size of the destination array on that axis) then it is fine. Does that sound like it's caused by the same underlying bug?

@bmerry Prior to my crude fix, I did in fact observe different behaviour depending on how I expressed my slices, even though they supposedly were equivalent. Whether I got a segmentation fault or just wrong results I do not remember. Try implementing the crude fix above of either myself or @theacetoace, I don't find it unlikely that it solves your problem.

Though really I would like to hear what @h5py have to say about this. It seems like a critical bug, the issue is getting old and they havn't responded at all...

**Comment by takluyver** [comment] 2021-01-15 10:56
Sorry about that; I think the fix @theacetoace described is a good one, because selecting part of the destination array shouldn't depend on the HDF5 dataset.

I've also just seen and responded to to #1792, which I think is a duplicate of this. If someone would like to do a PR, it would be great if you can add a test, probably in this class:

https://github.com/h5py/h5py/blob/552a4322c2523c01e4344beaa594df2d0eb93ee2/h5py/tests/test_dataset.py#L215

**Comment by bmerry** [comment] 2021-01-18 09:02
I'll take a look at strengthening that unit test.

**Closed** 2021-01-19 08:39 UTC
Labels: bug, pull-request-welcome
