### ISSUE TITLE
SystemError with custom destructor and python3.4

### ISSUE THREAD

**Issue by Xarthisius** [h5py/h5py#534] opened 2015-01-15 16:09 UTC
I'm not quite sure it's a *bug* in h5py, but I hope you'll help me with your expertise. Following code
```
import h5py

class HDF5FileHandler(object):
    handle = None
    def __init__(self, filename):
        self.handle = h5py.File(filename, 'r')

    def __del__(self):
        if self.handle is not None:
            self.handle.close()


a = HDF5FileHandler("/home/xarth/test.h5")
```
with *h5py-2.4.0* and *python3.4* yields:
```
Exception ignored in: <bound method HDF5FileHandler.__del__ of <__main__.HDF5FileHandler object at 0x7fdfe25ec240>>
Traceback (most recent call last):
  File "h.py", line 10, in __del__
  File "/usr/lib64/python3.4/site-packages/h5py/_hl/files.py", line 243, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/var/tmp/portage/dev-python/h5py-2.4.0/work/h5py-2.4.0/h5py/_objects.c:2705)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/var/tmp/portage/dev-python/h5py-2.4.0/work/h5py-2.4.0/h5py/_objects.c:2662)
  File "h5py/h5f.pyx", line 230, in h5py.h5f.get_obj_ids (/var/tmp/portage/dev-python/h5py-2.4.0/work/h5py-2.4.0/h5py/h5f.c:3401)
  File "h5py/h5i.pyx", line 37, in h5py.h5i.wrap_identifier (/var/tmp/portage/dev-python/h5py-2.4.0/work/h5py-2.4.0/h5py/h5i.c:1112)
SystemError: Parent module 'h5py' not loaded, cannot perform relative import
```
That only happens when file handle is closed by garbage collector. Is there anything particularly wrong with `HDF5FileHandler.__del__`? Could it be mitigated somehow in a way that would be backward compatible with python2.7 and previous versions of h5py?

**Comment by andrewcollette** [comment] 2015-01-15 16:50
Closed by the garbage collector, or closed by the garbage collector when Python is shutting down?  Can't think why the module would not be available...

**Comment by Xarthisius** [comment] 2015-01-15 17:16
When Python is shutting down. However, in the original problem that led to this report I'm looping over h5 files and get following tracebacks:

```
Opened /home/xarth/codes/yt_data/Orbit/orbit_hdf5_chk_0001
/usr/lib64/python3.4/site-packages/h5py/_hl/files.py:256: RuntimeWarning: Found murdered identifier 140144891986712 of kind <class 'NoneType'> HDF5 id 632516000
  self.id.close()
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
Traceback (most recent call last):
  File "h5py/_objects.pyx", line 197, in h5py._objects.ObjectID.__dealloc__ (/dev/shm/portage/dev-python/h5py-2.4.0/work/h5py-2.4.0/h5py/_objects.c:4571)
KeyError: 140144891986712
Opened /home/xarth/codes/yt_data/Orbit/orbit_hdf5_chk_0008
Opened /home/xarth/codes/yt_data/Orbit/orbit_hdf5_chk_0029
/usr/lib64/python3.4/site-packages/h5py/_hl/files.py:256: RuntimeWarning: Found murdered identifier 140144890500152 of kind <class 'NoneType'> HDF5 id 632516000
  self.id.close()
/usr/lib64/python3.4/site-packages/h5py/_hl/files.py:256: RuntimeWarning: Found murdered identifier 140144889898688 of kind <class 'NoneType'> HDF5 id 632516000
  self.id.close()
Exception ignored in: 'h5py._objects.ObjectID.__dealloc__'
```
In the original code `HDF5FileHandler` is used to just open the file and check if certain attribute exists. I'll try to prepare reduced test case for that too, in case it's a separate issue

**Comment by andrewcollette** [comment] 2015-01-15 17:26
Wow, I thought that error message would be impossible:

https://github.com/h5py/h5py/blob/master/h5py/_objects.pyx#L122

I wonder if this is related to the PEP 442 changes in Python 3.4.  Can you reproduce either issue on Python 3.3 or earlier?

**Comment by Xarthisius** [comment] 2015-01-15 18:55
Both issues are gone with *python3.3*

**Closed** 2016-02-10 04:07 UTC
Labels: bug, no-action-taken

**Comment by akloster** [comment] 2016-06-08 19:25
I'm seeing this problem with Python 3.5. Very annoying.

**Comment by micheles** [comment] 2016-07-08 15:11
I have the same problem with Python 3.5. There is also the issue that in Python 3 registry.items() is a view, so when in line 127 you do a `del registry[python_id]` then you get an error

   RuntimeError: dictionary changed size during iteration

You can solved this by changing the loop into

 for python_id, ref in list(registry.items())

Still, the reason why the impossible condition happens baffles me. I cannot reproduce this reliably, it happen on a project I have on travis, twice in about 40 runs.

**Comment by pitrou** [comment] 2016-11-15 08:52
See PR #776 for a fix to the "dictionary changed size during iteration" issue.

**Comment by r-bierman** [comment] 2021-12-07 23:59
I had a similar custom deconstructor error using h5py v3, but switching to v2.10 worked

```
import h5py

class HDF5(object):
    """
    Wrapper class around spatial HDF5 file
    """
    def __init__(self, hdf5_path):
        self.hdf5_path = hdf5_path
        self.f = h5py.File(self.hdf5_path,'r')

    def __del__(self):
        if self.f is not None:
            self.f.close()

    def list_genes(self):
        pass

```

```
Exception ignored in: <bound method HDF5.__del__ of <SRRS.hdf5.HDF5 object at 0x7f19f99186d8>>
Traceback (most recent call last):
  File "/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/src/SRRS/hdf5.py", line 29, in __del__
  File "/oak/stanford/groups/horence/rob/isoform_localizations/SRRS/dev_env/lib/python3.6/site-packages/h5py/_hl/files.py", line 446, in close
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 275, in h5py.h5f.get_obj_ids
  File "h5py/h5i.pyx", line 40, in h5py.h5i.wrap_identifier
ModuleNotFoundError: import of 'h5py' halted; None in sys.modules
```
