### ISSUE TITLE
Track order and attribute updating bug

### ISSUE THREAD

**Issue by woutdenolf** [h5py/h5py#1641] opened 2020-08-14 16:35 UTC
* h5py 2.10.0
* python 3.7, debian 10
* hdf5 1.10.4

Reproduce the error (runs fine with `track_order=False`):

```python
import h5py

with h5py.File("test.h5", mode="w", track_order=True) as f:
    f.attrs["file_time"] = "some-time-stamp"
    f.attrs["file_name"] = f.filename
    f.attrs["HDF5_Version"] = str(h5py.version.hdf5_version)
    f.attrs["h5py_version"] = str(h5py.version.version)
    f.attrs["creator"] = "Bliss"
    f.attrs["creator_version"] = "1.0"
    f.attrs["NX_class"] = "NXroot"
    f.attrs["file_update_time"] = "some-time-stamp"

with h5py.File("test.h5", mode="a", track_order=True) as f:
    f.attrs["file_update_time"] = "some-time-stamp"
```

Traceback:

```python
Traceback (most recent call last):
  File "test.py", line 14, in <module>
    f.attrs["file_update_time"] = "some-time-stamp"
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File ".../lib/python3.7/site-packages/h5py/_hl/attrs.py", line 100, in __setitem__
    self.create(name, data=value)
  File ".../lib/python3.7/site-packages/h5py/_hl/attrs.py", line 217, in create
    h5a.rename(self._id, self._e(tempname), self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5a.pyx", line 118, in h5py.h5a.rename
RuntimeError: Can't rename attribute (record is already in B-tree)
```

**Comment by dota17** [comment] 2020-08-15 03:39
@woutdenolf  What I found is the `track_order` can effect the result, but is not the key point, the number of attributes can really effect the result. The example code you post is exactly having 8 attributes, if its number less than 8, the code will run fine no matter `track_order` is true or false. 

I guess this is closely relate to the `attr-phase`, which you can see some detail info from docs [H5Pset_attr_phase_change](https://portal.hdfgroup.org/display/HDF5/H5P_SET_ATTR_PHASE_CHANGE)

**Comment by vasole** [comment] 2020-08-15 10:12
@dota17 Thank you! Never heard about that function.

If I understood well, to be able to achieve what the open poster wants at the root level["/"], one needs

- H5Pset_attr_phase_change accessible from h5py and
- either to be able to pass its parameters to h5py.File or to combine track_order=True with a call to H5Pset_attr_phase_change setting the input arguments max_compact and min_dense to 0.

**Comment by dota17** [comment] 2020-08-17 01:31
Duplicate of https://github.com/h5py/h5py/issues/1385

**Comment by takluyver** [comment] 2020-08-19 12:33
Thanks, I'll close this as a duplicate.

**Closed by takluyver** 2020-08-19 12:33 UTC

**Comment by kmuehlbauer** [comment] 2023-01-12 07:52
See upstream https://github.com/HDFGroup/hdf5/issues/1388 for details.
