### ISSUE TITLE
confuse group

### ISSUE THREAD

**Issue by 631068264** [h5py/h5py#893] opened 2017-06-02 14:53 UTC
MacOS 10.11 Python2.7 h5py 2.7

```
class Stash(object):
    path = os.path.join(os.path.dirname(os.path.dirname(__file__)), "stash")
    file_name = u"strategy.hdf5"

    def __init__(self, group_name):
        self.file_path = os.path.join(self.path, self.file_name)
        self.group_name = group_name
        with h5py.File(self.file_path, 'w') as f:
            f.create_group(group_name)

    def get(self, key):
        try:
            with h5py.File(self.file_path, 'r') as f:
                result = f[self.group_name][key]
            return result
        except Exception as e:
            logger.get("run-log").error("[GET:%s]:Key Error %s" % (key, self.file_path))

    def set(self, key, value):
        with h5py.File(self.file_path, 'w') as f:
            f[self.group_name][key] = value

    def delete(self, key):
        try:
            with h5py.File(self.file_path, 'a') as f:
                del f[self.group_name][key]
        except Exception as e:
            logger.get("run-log").error("[DEL:%s]:Key Error %s" % (key, self.file_path))

    def get_file(self):
        return h5py.File(self.file_path, 'w')
```

Then I write a Test:

```
stash = Stash(u"macd")
key = u"macd_1_golden_cross_uppper_0"
fail_key = u"macd_2_golden_cross_uppper_0"
stash.set(key, False)
result = stash.get(key)
print result
print type(result)

stash.delete(key)
stash.get(fail_key)
```

I get an error , it's very strange and confuse I have been create a group , why I can't read it ?
```
Traceback (most recent call last):
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/test_single_st.py", line 118, in <module>
    stash.set(key, False)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/base/stash.py", line 35, in set
    f[self.group_name][key] = value
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2798)
  File "/Users/wyx/bitcoin_workspace/fibo-strategy/.env/lib/python2.7/site-packages/h5py/_hl/group.py", line 169, in __getitem__
    oid = h5o.open(self.id, self._e(name), lapl=self._lapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2840)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/_objects.c:2798)
  File "h5py/h5o.pyx", line 190, in h5py.h5o.open (/private/var/folders/my/m6ynh3bn6tq06h7xr3js0z7r0000gn/T/pip-wdzlRM-build/h5py/h5o.c:3734)
KeyError: "Unable to open object (Object 'macd' doesn't exist)"
```

**Comment by tacaswell** [comment] 2017-06-09 21:36
The issue is that you are always opening the file in 'w' mode (see http://docs.h5py.org/en/latest/high/file.html#opening-creating-files) which truncates (effectively deleting the previous file).  You want to be opening it in `set` (and probably `delete`) with `'r+'` and `'a'` in `__init__` (or the second `Stash` object will blow away the entries from the first).

Having the file path to a class attribute is going to lead to race conditions between processes (which will lead to weird errors coming out of the underlying hdf5 library).

I would also suggest that you use `__getitem__`, `__setitem__` and `__delitem__` magic methods (see https://docs.python.org/3.6/reference/datamodel.html#object.__getitem__ and friends) so that your stash objects have the same API as `dict`.

Closing as I do not think this is a bug in h5py

**Closed by tacaswell** 2017-06-09 21:36 UTC
