### ISSUE TITLE
FYI: `h5py.highlevel` is no longer (since 2.8.0) available upon `import h5py`

### ISSUE THREAD

**Issue by yarikoptic** [h5py/h5py#1063] opened 2018-06-27 18:08 UTC
Feel free to close, just now mentioned that our conda update broke because of this so decided to share in case you would like to mitigate possible fallouts ;)

NB in the output below I've removed the annoying warning of 2.7.1
```shell
(git)hopa:~/proj/misc/h5py[tags/2.7.1^0]git
$> python -c 'import h5py; print h5py.highlevel'
<module 'h5py.highlevel' from 'h5py/highlevel.pyc'>

(git)hopa:~/proj/misc/h5py[tags/2.7.1^0]git
$> git co 2.8.0                                 
Previous HEAD position was 4817feb REL: 2.7.1
HEAD is now at dd51465 REL: 2.8.0

(git)hopa:~/proj/misc/h5py[tags/2.8.0^0]git
$> python -c 'import h5py; print h5py.highlevel'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
AttributeError: 'module' object has no attribute 'highlevel'
```

**Comment by tacaswell** [comment] 2018-06-28 04:50
closing as duplicate of https://github.com/h5py/h5py/issues/1046

**Closed by tacaswell** 2018-06-28 04:50 UTC
