### ISSUE TITLE
Possible byte order glitch related to opaque types

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#428] opened 2014-04-16 15:27 UTC
From the list:

I have a problem to open a hdf5 file with h5py (using h5py-2.2.1) containing variable length strings when the file is created on a x86 cluster (little endian) and read on a power cluster (big endian).

I do not have any issue with fixed length strings.

I can read and write a file with h5py containing variable length strings if I read it using the same system I used to create the file. I have this error when I try to read the power file on the x86 cluster and the x86 file on the power cluster :

Failed to find converter for 8 -> PYTHON:OBJECT

I am able to dump the info from the files using h5dum without any problem (any cluster can dump the info from both files without any issue).

Comparing the byte information (the files have exactly the same size), only a few bytes are different between the 2 files. I was wondering if one of this byte was referring to the endianness of the file which could impact how the length of the strings are stored.

Here is the code I used to read and then write the file on both systems :

To write:

```
import h5py
file = h5py.File('vlstring_p7.h5','w')
str_type = h5py.new_vlen(str)
dataset = file.create_dataset("DSvariable",(4000,), dtype=str_type)
data=()
for i in range(1000):
    data += ("Parting", " is such", " sweet", " sorrow...")
dataset[...] = data
file.close()
```

To read:

```
import h5py
file = h5py.File('vlstring_p7.h5', 'r')
dataset = file['DSvariable']
data_out = dataset[...]
for i in range(4):  
    print "DSvariable[",i,"]", "'"+data_out[i]+"'", "has length", len(data_out[i])

print data_out
file.close()
```

**Comment by andrewcollette** [comment] 2016-03-28 13:22
Update via email from a user:

I have investigated h5py issue #428, "Possible byte order glitch related to opaque types"

It seems that, in HDF5, fixed-length string datatypes are flagged as non-endian, but when they are converted to variable-length the base datatype becomes H5T_NATIVE_UCHAR, which is flagged with an endianness despite being a single byte.

In h5py, the vlen2str type converter is registered as HARD, which causes only an exact data-type to match, and the variable-length string with opposite endianness will not match. This causes the bug to occur. I have found two possible solutions:
1. Register the converter as SOFT, so that it matches for any VLEN datatype. In this case, the converter function would probably have to be modified to check H5Tis_variable_str() so that it doesn't try to convert non-string VLEN types.
2. Register the converter twice, for both endiannesses.

**Comment by tillea** [comment] 2016-09-10 20:50
Any chance that this will be fixed in the next couple of weeks?  If not I need to exclude some hardware architectures for a Debian package I'm maintaining.

**Comment by tillea** [comment] 2018-04-24 15:29
Any news for this issue?

**Comment by tillea** [comment] 2018-12-19 14:01
Hi again.  Did you managed to clean up string handling?

**Comment by rposts** [comment] 2020-06-12 14:43
Hi there - I opened a similar issue https://github.com/h5py/h5py/issues/1554 which I found to also occur on s390x architecture (big-endian).  Are there any updates on this issue as root cause looks the same?

Thanks.

**Comment by tillea** [comment] 2020-06-12 20:28
On Fri, Jun 12, 2020 at 07:44:08AM -0700, Rishi Misra wrote:
> Hi there - I opened a similar issue https://github.com/h5py/h5py/issues/1554 which I found to also occur on s390x architecture (big-endian).  Are there any updates on this issue as root cause looks the same?

Sorry, I've lost track in this issue.

Kind regards

    Andreas.

-- 
http://fam-tille.de

**Comment by rposts** [comment] 2020-06-12 20:32
@aragilar - any updates - Thx!

**Closed** 2020-08-09 14:16 UTC
Labels: bug, pull-request-welcome, string/unicode usage, vlen
