### ISSUE TITLE
h5py 2.6.0

### ISSUE THREAD

**Issue by Mr-Usama** [h5py/h5py#2050] opened 2022-02-09 11:30 UTC
I am using conda 3.8 :

C:\Users\Hp\PycharmProjects\LipNet>pip install h5py==2.6.0
Collecting h5py==2.6.0
  Using cached h5py-2.6.0.tar.gz (245 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy>=1.6.1 in c:\users\hp\anaconda3\lib\site-packages (from h5py==2.6.0) (1.20.1)
Requirement already satisfied: six in c:\users\hp\anaconda3\lib\site-packages (from h5py==2.6.0) (1.15.0)
Building wheels for collected packages: h5py
  Building wheel for h5py (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [133 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\h5py
      copying h5py\highlevel.py -> build\lib.win-amd64-3.8\h5py
      copying h5py\ipy_completer.py -> build\lib.win-amd64-3.8\h5py
      copying h5py\version.py -> build\lib.win-amd64-3.8\h5py
      copying h5py\__init__.py -> build\lib.win-amd64-3.8\h5py
      creating build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\attrs.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\base.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\dataset.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\datatype.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\dims.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\files.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\filters.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\group.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\selections.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\selections2.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\__init__.py -> build\lib.win-amd64-3.8\h5py\_hl
      creating build\lib.win-amd64-3.8\h5py\tests
      copying h5py\tests\common.py -> build\lib.win-amd64-3.8\h5py\tests
      copying h5py\tests\__init__.py -> build\lib.win-amd64-3.8\h5py\tests
      creating build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\common.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_attrs.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_attrs_data.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_base.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_dataset.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_datatype.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_dimension_scales.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_file.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_group.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5f.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5p.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5t.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_objects.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_selections.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_slicing.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\__init__.py -> build\lib.win-amd64-3.8\h5py\tests\old
      creating build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_attribute_create.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_dataset_getitem.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_dataset_swmr.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_datatype.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_dims_dimensionproxy.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_file.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_threads.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\__init__.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      running build_ext
      Autodetection skipped [Could not find module 'libhdf5.so' (or one of its dependencies). Try using the full path with constructor syntax.]
      C:\Users\Hp\anaconda3\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring
 its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, se
e http://github.com/IntelPython/mkl-service
        from . import _distributor_init
      Traceback (most recent call last):
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
          from . import multiarray
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
          from . import overrides
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-uxiywjk8\h5py_0c1272f2307d46a68cbeefc46fec130c\setup.py", line 132, in <module>
          setup(
        File "C:\Users\Hp\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Hp\anaconda3\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Hp\anaconda3\lib\site-packages\wheel\bdist_wheel.py", line 299, in run
          self.run_command('build')
        File "C:\Users\Hp\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Hp\anaconda3\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Hp\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-uxiywjk8\h5py_0c1272f2307d46a68cbeefc46fec130c\setup_build.py", line 188, in run
          self.extensions = cythonize(self._make_extensions(config),
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-uxiywjk8\h5py_0c1272f2307d46a68cbeefc46fec130c\setup_build.py", line 72, in _make_extensions
          import numpy
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\__init__.py", line 145, in <module>
          from . import core
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
          raise ImportError(msg)
      ImportError:
     
      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
     
      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.
     
      We have compiled some common reasons and troubleshooting tips at:
     
          https://numpy.org/devdocs/user/troubleshooting-importerror.html
     
      Please note and check the following:
     
        * The Python version is: Python3.8 from "C:\Users\Hp\anaconda3\python.exe"
        * The NumPy version is: "1.20.1"
     
      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.
     
      Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
     
      ********************************************************************************
                             Summary of the h5py configuration
     
          Path to HDF5: None
          HDF5 Version: '1.8.4'
           MPI Enabled: False
      Rebuild Required: False
     
      ********************************************************************************
      Executing api_gen rebuild of defs
      Executing cythonize()
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for h5py
  Running setup.py clean for h5py
Failed to build h5py
Installing collected packages: h5py
  Attempting uninstall: h5py
    Found existing installation: h5py 2.10.0
    Uninstalling h5py-2.10.0:
      Successfully uninstalled h5py-2.10.0
  Running setup.py install for h5py ... error
  error: subprocess-exited-with-error

  × Running setup.py install for h5py did not run successfully.
  │ exit code: 1
  ╰─> [134 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\h5py
      copying h5py\highlevel.py -> build\lib.win-amd64-3.8\h5py
      copying h5py\ipy_completer.py -> build\lib.win-amd64-3.8\h5py
      copying h5py\version.py -> build\lib.win-amd64-3.8\h5py
      copying h5py\__init__.py -> build\lib.win-amd64-3.8\h5py
      creating build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\attrs.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\base.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\dataset.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\datatype.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\dims.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\files.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\filters.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\group.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\selections.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\selections2.py -> build\lib.win-amd64-3.8\h5py\_hl
      copying h5py\_hl\__init__.py -> build\lib.win-amd64-3.8\h5py\_hl
      creating build\lib.win-amd64-3.8\h5py\tests
      copying h5py\tests\common.py -> build\lib.win-amd64-3.8\h5py\tests
      copying h5py\tests\__init__.py -> build\lib.win-amd64-3.8\h5py\tests
      creating build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\common.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_attrs.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_attrs_data.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_base.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_dataset.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_datatype.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_dimension_scales.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_file.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_group.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5f.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5p.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_h5t.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_objects.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_selections.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\test_slicing.py -> build\lib.win-amd64-3.8\h5py\tests\old
      copying h5py\tests\old\__init__.py -> build\lib.win-amd64-3.8\h5py\tests\old
      creating build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_attribute_create.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_dataset_getitem.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_dataset_swmr.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_datatype.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_dims_dimensionproxy.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_file.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\test_threads.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      copying h5py\tests\hl\__init__.py -> build\lib.win-amd64-3.8\h5py\tests\hl
      running build_ext
      Autodetection skipped [Could not find module 'libhdf5.so' (or one of its dependencies). Try using the full path with constructor syntax.]
      C:\Users\Hp\anaconda3\lib\site-packages\numpy\__init__.py:143: UserWarning: mkl-service package failed to import, therefore Intel(R) MKL initialization ensuring
 its correct out-of-the box operation under condition when Gnu OpenMP had already been loaded by Python process is not assured. Please install mkl-service package, se
e http://github.com/IntelPython/mkl-service
        from . import _distributor_init
      Traceback (most recent call last):
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\__init__.py", line 22, in <module>
          from . import multiarray
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\multiarray.py", line 12, in <module>
          from . import overrides
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\overrides.py", line 7, in <module>
          from numpy.core._multiarray_umath import (
      ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.
     
      During handling of the above exception, another exception occurred:
     
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-uxiywjk8\h5py_0c1272f2307d46a68cbeefc46fec130c\setup.py", line 132, in <module>
          setup(
        File "C:\Users\Hp\anaconda3\lib\site-packages\setuptools\__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "C:\Users\Hp\anaconda3\lib\distutils\core.py", line 148, in setup
          dist.run_commands()
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Hp\anaconda3\lib\site-packages\setuptools\command\install.py", line 61, in run
          return orig.install.run(self)
        File "C:\Users\Hp\anaconda3\lib\distutils\command\install.py", line 545, in run
          self.run_command('build')
        File "C:\Users\Hp\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Hp\anaconda3\lib\distutils\command\build.py", line 135, in run
          self.run_command(cmd_name)
        File "C:\Users\Hp\anaconda3\lib\distutils\cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "C:\Users\Hp\anaconda3\lib\distutils\dist.py", line 985, in run_command
          cmd_obj.run()
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-uxiywjk8\h5py_0c1272f2307d46a68cbeefc46fec130c\setup_build.py", line 188, in run
          self.extensions = cythonize(self._make_extensions(config),
        File "C:\Users\Hp\AppData\Local\Temp\pip-install-uxiywjk8\h5py_0c1272f2307d46a68cbeefc46fec130c\setup_build.py", line 72, in _make_extensions
          import numpy
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\__init__.py", line 145, in <module>
          from . import core
        File "C:\Users\Hp\anaconda3\lib\site-packages\numpy\core\__init__.py", line 48, in <module>
          raise ImportError(msg)
      ImportError:
     
      IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
     
      Importing the numpy C-extensions failed. This error can happen for
      many reasons, often due to issues with your setup or how NumPy was
      installed.
     
      We have compiled some common reasons and troubleshooting tips at:
     
          https://numpy.org/devdocs/user/troubleshooting-importerror.html
     
      Please note and check the following:
     
        * The Python version is: Python3.8 from "C:\Users\Hp\anaconda3\python.exe"
        * The NumPy version is: "1.20.1"
     
      and make sure that they are the versions you expect.
      Please carefully study the documentation linked above for further help.
     
      Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
     
      ********************************************************************************
                             Summary of the h5py configuration
     
          Path to HDF5: None
          HDF5 Version: '1.8.4'
           MPI Enabled: False
      Rebuild Required: False
     
      ********************************************************************************
      Executing cythonize()
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  WARNING: No metadata found in c:\users\hp\anaconda3\lib\site-packages
  Rolling back uninstall of h5py
  Moving to c:\users\hp\anaconda3\lib\site-packages\h5py-2.10.0.dist-info\
   from C:\Users\Hp\anaconda3\Lib\site-packages\~5py-2.10.0.dist-info
  Moving to c:\users\hp\anaconda3\lib\site-packages\h5py\
   from C:\Users\Hp\anaconda3\Lib\site-packages\~5py
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> h5py

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

**Comment by tacaswell** [comment] 2022-02-09 15:49
This looks like you have broken your conda enviroment by mixing using pip and conda to install compiled extensions (which I suspect because you are getting numpy import errors in those logs) and you are also missing libhdf5.  I suggest following steps:

 1. delete and re-create your conda installation.  Once the packaging has gone sideways, it is almost easier to start fresh than try to fix an existing enviroment.  I also _strongly_ suggest never doing any work in the base conda environment and always creating new ones for you work or when you want to upgrade.  That way if it goes badly, you can delete the new one and go back to the one that was just working ;) 
 2. stick with the conda(-forge) packging of h5py if possible.  That will make sure that all of your compiled extensions are consistent with each other.  If you can do this you are done :)
 3. if not, stick to version of h5py for which we published wheels for windows (look for the `.whl` files in e.g. https://pypi.org/project/h5py/2.6.0/#files) for your version of Python.  You can make pip only install wheels via `pip install h5py --only-binary h5py`. If you go this route and are using pip on top of conda, I suggest you treat it as a latch, once you use `pip` never go back to using `conda` to install things.  If you can solve your problems this way you are done :)
 4. if you need old versions of h5py on new versions of Python and neither conda(-forge) or pypi has pre-built binaries, you will need to compile from source.  Please see https://docs.h5py.org/en/stable/build.html#source-installation-on-windows and make sure you have all of the prerequisites (including libhdf5 and a compiler) available.

I am going to close this as I do not think there is any action we can take on the h5py side as this is a local environment / installation issues not a bug in the library.  Best of luck @Mr-Usama !

**Closed by tacaswell** 2022-02-09 15:49 UTC
