### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [h5py/h5py#1682] opened 2020-09-29 05:55 UTC
**Summary**
Installing h5py on aarch64 via pip using command "pip3 install h5py" tries to build wheel from source code

**Problem description**
h5py doesn't have wheel for aarch64 on PyPI repository. So, while installing h5py via pip on aarch64, pip builds wheel for same resulting in it takes more time to install h5py. Making wheel available for aarch64 will benefit aarch64 users by minimizing h5py installation time.

**Expected Output**
Pip should be able to download h5py wheel from PyPI repository rather than building it from source code.

@h5py-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make h5py wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by takluyver** [comment] 2020-09-29 11:10
I've been working recently on automating wheel builds as part of this repository (#1674), but this doesn't include ARM. I'm not aware of free CI services which give us the option to run on aarch64.

I kind of agree with [this comment](https://github.com/pypa/manylinux/issues/84#issuecomment-623064775) from one of the NumPy maintainers. Just because the manylinux definition now supports more architectures, does not mean it's reasonable to expect every open-source project to provide precompiled wheels for each architecture. You still have the option to install from source, and you may be able to use more specific repositories like [piwheels](https://www.piwheels.org/project/h5py/).

**Comment by odidev** [comment] 2020-09-30 07:55
@takluyver , thank you for your quick response. CI services like travis gives us the option to run aarch64 builds. For azure-pipelines, we can use qemu to run an aarch64 build on x86 machine. I am able to successfully run azure-pipeline using qemu for few packages for aarch64 platform.

Adding aarch64 wheel will benefit aarch64 users to install the packages quickly.

Please let me know your feedback and suggestions regarding this.

**Comment by aragilar** [comment] 2020-09-30 09:12
I'm wary of depending on qemu (or any emulator) for producing wheels, as there may be subtle incompatibilities (I know the linux distros require being able to build natively to avoid this), and because it will likely be quite slow to build/test.

If there was an index of locations/indices (which would include piwheels) to get custom build wheels for specific hardware/software (maybe run by PyPA or some other trusted org), I think we'd link to that in the installation docs (we can link to pywheels directly, but it would be nice if there was a central place to link to so we don't end up with a lots of links to dead/unmaintained lists).

**Comment by rhenwood-arm** [comment] 2020-09-30 16:34
(I'm working with @odidev). I recognize the possible problems with emulation. There are alternatives, including cross-compiling. [Dockcross](https://github.com/dockcross/dockcross/) has a nice container package to make the cross-compiling environment manageable. I've written [an example](https://github.com/ARM-software/developer/blob/master/solutions/infrastructure/languages-and-libraries/python/multi-platform.md#using-dockcross) of it usage.
How does that sound?

**Comment by mattsplats** [comment] 2020-10-06 19:43
@takluyver TravisCI will build directly on aarch64 now, this is what many large projects are using:
https://blog.travis-ci.com/2020-09-11-arm-on-aws

It's actually fairly trivial to add an aarch64 build to travis.yml, just need to collect the wheel and upload it to PyPI at the end.

**Comment by AGSaidi** [comment] 2020-10-06 19:58
I'd also like to see a aarch64/arm64 wheel and i'm happy to help.

**Comment by janaknat** [comment] 2020-10-08 17:56
+1 for aarch64/arm64 wheels.

An example of pandas building aarch64 wheels using Travis-CI: https://github.com/MacPython/pandas-wheels/pull/99
Azure is used to build the x86 wheels: https://github.com/MacPython/pandas-wheels/blob/master/azure-pipelines.yml

We now have aarch64 pandas wheels available on PyPI: https://pypi.org/project/pandas/#files

**Comment by mattsplats** [comment] 2020-10-08 21:50
Created a PR to add aarch64 to the CI repo: https://github.com/MacPython/h5py-wheels/pull/12

I know there's been work to move CI to this repo - if necessary, we can reproduce the build here via Travis and multibuild.

**Comment by takluyver** [comment] 2020-11-03 09:48
Travis announced yesterday significant changes to what they offer. It's kind of unclear - one of my colleagues had an email which seemed to contradict the blog post - but in any case it looks like the allowance for open source projects is going to be severely curtailed. We will likely need to run less on Travis, not more. Issue #1733 discusses this.

**Comment by takluyver** [comment] 2021-03-05 17:54
It appears that [drone.io](https://cloud.drone.io/) has ARM builders and a free offering for open source projects (not clear what if any limits there are - the landing page just says 'gobs'). There is [some documentation](https://readme.drone.io/pipeline/docker/overview/), though it's not the most thorough, and parts of it are confusing because it seems to focus on hosting it yourself rather than using their servers.

Drone runs Docker for you, and it's apparently [not possible](https://github.com/joerick/cibuildwheel/issues/340) to launch Docker again from inside the container, so this would be a bit more complex than on other platforms where we call cibuildwheel and it manages Docker. We'd need to write the equivalent of what cibuildwheel does inside the container directly in the `.drone.yml` config.

Nonetheless, that might be the best option to explore for anyone who wants ARM wheels.

CI platforms, gotta collect 'em all!

**Comment by AGSaidi** [comment] 2021-06-23 14:40
CircleCI also has free Arm builders.

**Comment by takluyver** [comment] 2021-06-23 15:16
Yes, it [does seem to](https://circleci.com/build-environments/arm/). Although it's part of the 'free' plan (250 build minutes per week), but not the more generous open source offering. That's probably enough to work, but it might not leave much elbow room in busier weeks.

I think this is now waiting for someone to pick a CI service (Drone or Circle are the options I'm aware of) and try to set it up. And, ideally, pledge to help keep it running after it's merged. :slightly_smiling_face:

**Comment by AGSaidi** [comment] 2021-06-23 15:49
@takluyver do you have a particular preference on which CI tool? Travis does have a way to sponsor OSS infrastructure through a partner queue that AWS and Arm support. I'm happy to get h5py added to that or we could also use Circle but it currently has the limitation you mention. @JeffUnderhill

**Comment by kushalkoolwal** [comment] 2021-06-23 16:08
Last month Travis CI released [PQS](https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution) for their Arm64 environment which allows Open Source projects to build for free.

**Comment by takluyver** [comment] 2021-06-23 16:12
I don't have any strong preference.

I got the impression last year that Travis was pushing open source projects away to focus on paying users, which made me a bit hesitant to spend any time setting up CI there. Maybe that's changing now, given what @kushalkoolwal mentioned. :shrug:

**Comment by JeffUnderhill** [comment] 2021-06-23 16:45
Many services offering free capacity for OSS projects were subject to abuse from bitcoin miners etc... and had to change their offerings to stem/stop that abuse (most recently Docker did the same with their [Autobuilds capability](https://www.docker.com/blog/changes-to-docker-hub-autobuilds/)), TravisCI were the same but they are actively supporting OSS communities with new mechanisms that make it sustainable going forward and the [PQS](https://docs.travis-ci.com/user/billing-overview/#partner-queue-solution) mentioned by @kushalkoolwal above is one of those mechanisms.

**Closed** 2021-11-10 13:55 UTC
Labels: ci
