### ISSUE TITLE
Cython.Compiler.Errors.CompileError

### ISSUE THREAD

**Issue by davidedelvento** [h5py/h5py#532] opened 2015-01-14 18:45 UTC
I'm trying to compile h5py 2.4.0 from setup with fully mpi support. 

This is with:

python v2.7.7
gcc v4.8.2
hdf5-mpi v1.8.9
cython v0.18
numpy v1.8.1
mpi4py v1.3

I am doing what follows:

export CC=mpicc #the proper alias for the gcc with the mpi stuff enabled
python setup.py configure --hdf5=/proper/path/ --hdf5-version=1.8.9 --mpi

which spits:
running configure

---

```
                   Summary of the h5py configuration

Path to HDF5: '/proper/path/'
HDF5 Version: '1.8.9'
 MPI Enabled: True
```

Rebuild Required: True

---

(note that the autodetect fails with libhdf5.so: undefined symbol: MPI_Barrier)

When I run:
python setup.py build 

it spits:
running build
running build_py
creating build
creating build/lib.linux-x86_64-2.7
creating build/lib.linux-x86_64-2.7/h5py
copying h5py/**init**.py -> build/lib.linux-x86_64-2.7/h5py
copying h5py/highlevel.py -> build/lib.linux-x86_64-2.7/h5py
copying h5py/ipy_completer.py -> build/lib.linux-x86_64-2.7/h5py
copying h5py/version.py -> build/lib.linux-x86_64-2.7/h5py
creating build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/__init__.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/attrs.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/base.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/dataset.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/datatype.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/dims.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/files.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/filters.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/group.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/selections.py -> build/lib.linux-x86_64-2.7/h5py/_hl
copying h5py/_hl/selections2.py -> build/lib.linux-x86_64-2.7/h5py/_hl
creating build/lib.linux-x86_64-2.7/h5py/tests
copying h5py/tests/__init__.py -> build/lib.linux-x86_64-2.7/h5py/tests
copying h5py/tests/common.py -> build/lib.linux-x86_64-2.7/h5py/tests
creating build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/**init**.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/common.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_attrs.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_attrs_data.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_base.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_dataset.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_datatype.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_dimension_scales.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_group.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_h5.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_h5f.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_h5p.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_h5t.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_objects.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_selections.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
copying h5py/tests/old/test_slicing.py -> build/lib.linux-x86_64-2.7/h5py/tests/old
creating build/lib.linux-x86_64-2.7/h5py/tests/hl
copying h5py/tests/hl/**init**.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
copying h5py/tests/hl/test_dataset_getitem.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
copying h5py/tests/hl/test_dims_dimensionproxy.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
copying h5py/tests/hl/test_file.py -> build/lib.linux-x86_64-2.7/h5py/tests/hl
running build_ext
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##    ^

h5py/api_types_ext.pxd:15:4: 'mpi4py.MPI.pxd' not found
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##    ^

h5py/api_types_ext.pxd:15:4: 'MPI_Comm.pxd' not found
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##                            ^

h5py/api_types_ext.pxd:15:28: Name 'MPI_Comm' not declared in module 'mpi4py.MPI'
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##    ^

h5py/api_types_ext.pxd:15:4: 'MPI_Info.pxd' not found
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##                                      ^

h5py/api_types_ext.pxd:15:38: Name 'MPI_Info' not declared in module 'mpi4py.MPI'
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##    ^

h5py/api_types_ext.pxd:15:4: 'Comm.pxd' not found
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##                                                ^

h5py/api_types_ext.pxd:15:48: Name 'Comm' not declared in module 'mpi4py.MPI'
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##    ^

h5py/api_types_ext.pxd:15:4: 'Info.pxd' not found
## Error compiling Cython file:

...
# === Standard C library types and functions ==================================

include 'config.pxi'

IF MPI:
    from mpi4py.MPI cimport MPI_Comm, MPI_Info, Comm, Info
##                                                      ^

h5py/api_types_ext.pxd:15:54: Name 'Info' not declared in module 'mpi4py.MPI'
## Error compiling Cython file:

...
cdef herr_t H5Pset_libver_bounds(hid_t fapl_id, H5F_libver_t libver_low, H5F_libver_t libver_high) except *
cdef herr_t H5Pget_libver_bounds(hid_t fapl_id, H5F_libver_t *libver_low, H5F_libver_t *libver_high) except *
cdef herr_t H5Pset_alignment(hid_t plist_id, hsize_t threshold, hsize_t alignment) except *
cdef herr_t H5Pget_alignment(hid_t plist_id, hsize_t *threshold, hsize_t *alignment) except *
IF MPI:
    cdef herr_t H5Pset_fapl_mpio(hid_t fapl_id, MPI_Comm comm, MPI_Info info) except *
##                                                ^

h5py/defs.pxd:236:48: 'MPI_Comm' is not a type identifier
## Error compiling Cython file:

...
cdef herr_t H5Pset_libver_bounds(hid_t fapl_id, H5F_libver_t libver_low, H5F_libver_t libver_high) except *
cdef herr_t H5Pget_libver_bounds(hid_t fapl_id, H5F_libver_t *libver_low, H5F_libver_t *libver_high) except *
cdef herr_t H5Pset_alignment(hid_t plist_id, hsize_t threshold, hsize_t alignment) except *
cdef herr_t H5Pget_alignment(hid_t plist_id, hsize_t *threshold, hsize_t *alignment) except *
IF MPI:
    cdef herr_t H5Pset_fapl_mpio(hid_t fapl_id, MPI_Comm comm, MPI_Info info) except *
##                                                               ^

h5py/defs.pxd:236:63: 'MPI_Info' is not a type identifier
## Error compiling Cython file:

...
cdef herr_t H5Pset_alignment(hid_t plist_id, hsize_t threshold, hsize_t alignment) except *
cdef herr_t H5Pget_alignment(hid_t plist_id, hsize_t *threshold, hsize_t *alignment) except *
IF MPI:
    cdef herr_t H5Pset_fapl_mpio(hid_t fapl_id, MPI_Comm comm, MPI_Info info) except *
IF MPI:
    cdef herr_t H5Pget_fapl_mpio(hid_t fapl_id, MPI_Comm *comm, MPI_Info *info) except *
##                                                ^

h5py/defs.pxd:238:48: 'MPI_Comm' is not a type identifier
## Error compiling Cython file:

...
cdef herr_t H5Pset_alignment(hid_t plist_id, hsize_t threshold, hsize_t alignment) except *
cdef herr_t H5Pget_alignment(hid_t plist_id, hsize_t *threshold, hsize_t *alignment) except *
IF MPI:
    cdef herr_t H5Pset_fapl_mpio(hid_t fapl_id, MPI_Comm comm, MPI_Info info) except *
IF MPI:
    cdef herr_t H5Pget_fapl_mpio(hid_t fapl_id, MPI_Comm *comm, MPI_Info *info) except *
##                                                                ^

h5py/defs.pxd:238:64: 'MPI_Info' is not a type identifier

---

```
                   Summary of the h5py configuration

Path to HDF5: '/glade/apps/opt/hdf5-mpi/1.8.9/gnu/4.7.2/'
HDF5 Version: '1.8.9'
 MPI Enabled: True
```

Rebuild Required: True

---

Executing api_gen rebuild of defs
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/defs.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/_errors.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/_objects.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/_proxy.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5fd.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5z.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5i.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5r.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/utils.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/_conv.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5t.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5s.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5p.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5d.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5a.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5f.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5g.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5l.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5o.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5ds.pyx because it changed.
Compiling /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/h5ac.pyx because it changed.
Cythonizing /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/_conv.pyx
Traceback (most recent call last):
  File "setup.py", line 147, in <module>
    cmdclass = CMDCLASS,
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/distutils/command/build.py", line 127, in run
    self.run_command(cmd_name)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/glade/apps/opt/python/2.7.7/gnu-westmere/4.8.2/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/setup_build.py", line 130, in run
    force=config.rebuild_required or self.force)
  File "/glade/apps/opt/cython/0.18/gnu/4.7.2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 673, in cythonize
    cythonize_one(*args[1:])
  File "/glade/apps/opt/cython/0.18/gnu/4.7.2/lib/python2.7/site-packages/Cython/Build/Dependencies.py", line 737, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: /glade/scratch/ddvento/build/h5py/h5py-2.4.0-mpi/h5py/_conv.pyx

which looks like some problem between cython and mpi4py. I know very little about cython but if my understing is correct, this problem is due to:

h5py/api_types_ext.pxd:15:28: Name 'MPI_Comm' not declared in module 'mpi4py.MPI'

and if my understanding of mpi4py is correct, MPI_Comm is indeed not included (I know there is a version of mpi4py slightly newer than the one I am using, but I don't think that's the problem here -- I'd love to be proved wrong).

**Comment by andrewcollette** [comment] 2015-01-14 21:27
I think the problem is on this line:

``h5py/api_types_ext.pxd:15:4: 'mpi4py.MPI.pxd' not found``

For some reason, Cython is not able to find the ``mpi4py`` definitions file.  Subsequent errors appear to flow from this.

To start debugging, you could try to put this line by itself into a .pyx file and try to manually compile it with the ``cython`` command-line program.

**Comment by davidedelvento** [comment] 2015-01-15 22:46
Thanks for the catch. This seems indeed to be the root cause. 

However, that file is located in $MPI4PYPATH/site-packages/mpi4py/include/mpi4py/MPI.pxd -- and PYTHONPATH includes $MPI4PYPATH/site-packages

If I understand http://docs.cython.org/src/userguide/sharing_declarations.html#search-paths-for-definition-files correctly, though cython plaining ignores PYTHONPATH and only uses -I path search. In fact, if I call cython with -I  $MPI4PYPATH/site-packages/mpi4py/include/ my single-line pyx compiles to a .c

If that is correct, may I suggest that you add a --mpi4py=/proper/path/ to your setup.py and use the path as -I argument when calling cython?

Anyway, I tried to locate where cython is called in the build process to manually workaround this issue in my install, but couldn't. Do you mind guiding me in the search? Thanks!

**Comment by andrewcollette** [comment] 2015-01-16 20:15
Cython is called in setup_build.py, in the "run" method.  I'll tag this issue as an enhancement request for the ``--mpi4py`` option.

**Comment by davidedelvento** [comment] 2015-01-21 21:37
Thanks for pointing that out. Adding include_path = ["$MPI4PYPATH/site-packages/mpi4py/include/"] on line 131 of setup_build.py fixed my issue. 
You might also want to add the mpi4py requirement (for the parallel version) in the docs too.

**Comment by hschilling** [comment] 2015-02-09 23:00
I have the same problem. I am puzzled by this last post. Line 131 is in the middle of the string that gets written to the config file. Is that where it is supposed to go ? I actually did try it with no luck.

I can try some more debugging with as Andrew suggested as well.

Thanks in advance

**Comment by davidedelvento** [comment] 2015-02-09 23:15
Maybe you are on a slightly different version or something? Anyway, this is the full thing that I changed:

  self.extensions = cythonize(self._make_extensions(config),
                            include_path = ["/path-to-my/site-packages/mpi4py/include/"],
                            force=config.rebuild_required or self.force)

The original version did not have the include_path on cythonize but did have everything else.

Hope this helps.

**Comment by hschilling** [comment] 2015-02-10 02:04
David, that worked great ! Specifically, I used ( after importing mpi4py, of course )

                            include_path = [mpi4py.get_include(),],

Thanks for the response.

**Comment by aragilar** [comment] 2017-12-05 02:13
Fixed by https://github.com/h5py/h5py/pull/640

**Closed by aragilar** 2017-12-05 02:13 UTC
Labels: enhancement
