### ISSUE TITLE
Wrong error when h5 file broken?

### ISSUE THREAD

**Issue by brorfred** [h5py/h5py#704] opened 2016-04-25 17:04 UTC
The error message when trying to read a broken h5 file is a bit confusing. The raise message is 

`error message = 'file exists'
`

Where h5ls says

`unable to open file
`

Full trace:

```
/Users/bror/git/NWA_Omega/pco2_maps.pyc in process_all_months(datadir)
     77     flist = glob.glob(os.path.join(datadir, "nwa_mon_*_*.h5"))
     78     for fn in flist:
---> 79         h5f = h5py.File(fn)
     80         try:
     81             salt = h5f["salt"][:-1, :-1]

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/files.pyc in __init__(self, name, mode, driver, libver, userblock_size, swmr, **kwds)
    270 
    271                 fapl = make_fapl(driver, libver, **kwds)
--> 272                 fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
    273 
    274                 if swmr_support:

/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/h5py/_hl/files.pyc in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    115                 fid = h5f.open(name, h5f.ACC_RDONLY, fapl=fapl)
    116             except IOError:
--> 117                 fid = h5f.create(name, h5f.ACC_EXCL, fapl=fapl, fcpl=fcpl)
    118     else:
    119         raise ValueError("Invalid mode; must be one of r, r+, w, w-, x, a")

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/opt/local/var/macports/build/_opt_mports_dports_python_py-h5py/py27-h5py/work/h5py-2.6.0/h5py/_objects.c:2684)()

h5py/_objects.pyx in h5py._objects.with_phil.wrapper (/opt/local/var/macports/build/_opt_mports_dports_python_py-h5py/py27-h5py/work/h5py-2.6.0/h5py/_objects.c:2642)()

h5py/h5f.pyx in h5py.h5f.create (/opt/local/var/macports/build/_opt_mports_dports_python_py-h5py/py27-h5py/work/h5py-2.6.0/h5py/h5f.c:2105)()

IOError: Unable to create file (Unable to open file: name = '/volumes/mybookecoa/ecoa_nwa_sat/nwa_mon_2004_08.h5', errno = 17, error message = 'file exists', flags = 15, o_flags = a02)
```

Checking what's wrong:

```
In [8]: ls /Volumes/myBookECOA/ecoa_nwa_sat/nwa_mon_2004_08.h5
/Volumes/myBookECOA/ecoa_nwa_sat/nwa_mon_2004_08.h5

In [9]: !h5ls /Volumes/myBookECOA/ecoa_nwa_sat/nwa_mon_2004_08.h5
/Volumes/myBookECOA/ecoa_nwa_sat/nwa_mon_2004_08.h5: unable to open file
```

**Comment by duncanparkes** [comment] 2016-09-06 10:36
I think part of what's going on here is that the default mode for opening a file with `h5py.File` is `r+` (read and append). If you change line 75 of your code to 

```
h5f = h5py.File(fn, 'r')
```

you'll get a more sensible looking error message.

**Comment by aragilar** [comment] 2017-12-09 11:16
While technically #940 is a duplicate of this, #940 has more discussion about what the appropriate solution might be.

**Closed by aragilar** 2017-12-09 11:16 UTC
Labels: bug-in-external-lib, duplicate
