### ISSUE TITLE
test_register_filter fails on some (32bit?) arches: OverflowError: Python int too large to convert to C ssize_t

### ISSUE THREAD

**Issue by drew-parsons** [h5py/h5py#2315] opened 2023-09-29 09:23 UTC
debian builds of h5py 3.9.0 are failing on some less common architectures, see the red blocks at https://buildd.debian.org/status/package.php?p=h5py

Arches affected by the same problem are  armel, i386 (i686),  hppa,  powerpc,  sparc64.  armhf is in progress.
edit: also affected: armhf, x32.

The build log for i386 for instance is https://buildd.debian.org/status/fetch.php?pkg=h5py&arch=i386&ver=3.9.0-1&stamp=1695926469&raw=0

The error occurs in test_register_filter (test_h5z.py):
```
_____________________________ test_register_filter _____________________________

    def test_register_filter():
        filter_id = 256  # Test ID
    
        @H5ZFuncT
        def failing_filter_callback(flags, cd_nelemts, cd_values, nbytes, buf_size, buf):
            return 0
    
        dummy_filter_class = H5ZClass2T(
            version=h5z.CLASS_T_VERS,
            id_=filter_id,
            encoder_present=1,
            decoder_present=1,
            name=b"dummy filter",
            can_apply=None,
            set_local=None,
            filter_=failing_filter_callback,
        )
    
>       h5z.register_filter(addressof(dummy_filter_class))

build/h5py/_debian_h5py_serial/tests/test_h5z.py:65: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
h5py/_debian_h5py_serial/_objects.pyx:54: in h5py._debian_h5py_serial._objects.with_phil.wrapper
    ???
h5py/_debian_h5py_serial/_objects.pyx:55: in h5py._debian_h5py_serial._objects.with_phil.wrapper
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

>   ???
E   OverflowError: Python int too large to convert to C ssize_t

h5py/_debian_h5py_serial/h5z.pyx:102: OverflowError
=========================== short test summary info ============================
FAILED build/h5py/_debian_h5py_serial/tests/test_h5z.py::test_register_filter
=========== 1 failed, 709 passed, 28 skipped, 3 deselected in 9.62s ============
```
I might have thought it was an issue with 32-bit architectures, except that sparc64 is 64-bit. The build on the 32-bit arch armhf is in progress. [Edit: armhf and x32 also affected]

```
Summary of the h5py configuration (i386)
---------------------------------

h5py    3.9.0
HDF5    1.10.10
Python  3.11.5 (main, Aug 29 2023, 15:31:31) [GCC 13.2.0]
sys.platform    linux
sys.maxsize     2147483647
numpy   1.24.2
cython (built with) 0.29.36
numpy (built against) 1.24.2
HDF5 (built against) 1.10.10
```

**Comment by drew-parsons** [comment] 2023-09-29 16:27
l.110 in h5z.pyx
https://github.com/h5py/h5py/blob/9e7affa467812d80201294b88ae0f112e35d1af2/h5py/h5z.pyx#L102C21-L102C31
```
def register_filter(Py_ssize_t cls_pointer_address):
```
`register_filter` expects a `Py_ssize_t`, but [`addressof`](https://docs.python.org/3/library/ctypes.html#ctypes.addressof) returns an `int`.  Would this be the origin of the error?

h5z.register_filter function is new in h5py 3.9.0 (PR #2229) , which explains why I didn't see the error previously (this is the first debian build of 3.9.0 on these arches)

**Comment by takluyver** [comment] 2023-10-02 08:11
I think that's likely the cause of it. I'm guessing that because pointers are unsigned but Py_ssize_t is signed, it fails in the upper half of the address space. Perhaps we should be using `size_t` or some other type there instead.

**Comment by drew-parsons** [comment] 2023-10-02 08:24
I also suspect it might work if the `int` returned by `addressof` is cast into `ctypes.c_int`  (or their unsigned counterparts)

**Comment by takluyver** [comment] 2023-10-02 08:31
Ping @t20100 - `Py_ssize_t` doesn't seem to work to accept a pointer for `register_filter`, is it clear to you what it should be instead?

**Comment by t20100** [comment] 2023-10-02 11:56
Not sure what type to use. I'll look at this and try to find a machine to reproduce this issue.

**Comment by takluyver** [comment] 2023-10-02 12:49
Thanks!

@drew-parsons is there any easy way to test a small change on any of the machines used as build bots?

**Comment by drew-parsons** [comment] 2023-10-02 13:16
Not the build daemons directly (apart from uploading a new debian package version), but we have porterboxes I can easily log into.  If you'd like to be able to use the resources over the longer term, we could request a [guest account](https://dsa.debian.org/doc/guest-account/) for you.

**Comment by t20100** [comment] 2023-10-02 15:03
Still needs testing, but is the signed type is the issue, the following patch should fix it: it makes cython convert the Python int to `size_t` instead of `ssize_t` in the generated C code.
If the issue is that a `void *` cannot be fit into a `(s)size_t` then this won't fix it because cython's `uintptr_t` is `size_t`.

<details><summary>Patch</summary>

```
--- a/h5py/h5z.pyx
+++ b/h5py/h5z.pyx
@@ -11,6 +11,7 @@
     Filter API and constants.
 """
 
+from libc.stdint cimport uintptr_t
 from ._objects import phil, with_phil
 
 
@@ -99,7 +100,7 @@ def get_filter_info(int filter_code):
 
 
 @with_phil
-def register_filter(Py_ssize_t cls_pointer_address):
+def register_filter(uintptr_t cls_pointer_address):
     '''(INT cls_pointer_address) => BOOL
 
     Register a new filter from the memory address of a buffer containing a
```

</details>

**Comment by drew-parsons** [comment] 2023-10-02 16:05
That patch seems to be sufficient. It enables h5py to build on i386 and pass tests.

**Comment by t20100** [comment] 2023-10-03 07:03
Thanks for the tests!
I'll prepare a PR for this.

**Closed** 2023-10-04 09:14 UTC
