### ISSUE TITLE
bug when indexing with numpy integer array of size 1

### ISSUE THREAD

**Issue by SuperElectric** [h5py/h5py#584] opened 2015-06-10 14:20 UTC
Indexing a multidimensional Dataset with an numpy array of length 1 is treated the same as indexing with the integer it contains. This is inconsistent with numpy.ndarray's behavior, and with the behavior of Dataset when indexing it with a list or tuple of integers.

I am using h5py 2.2.1, the version used by Ubuntu 14.04 (the current long-term support version of Ubuntu).

Example, where `dset` is a Dataset of shape `(3, 4, 5, 6)`:

```
>> dset[[1], ...].shape  # indexing with a size-1 list produces expected shape
>> (1, 4, 5, 6)
>> dset[numpy.arange(1), ...].shape  # indexing with a size-1 ndarray does not
>> (4, 5, 6)
>> dset[numpy.arange(2), ...].shape  # ndarrays are ok as long as their size > 1
>> (2, 4, 5, 6)
```

**Comment by jakirkham** [comment] 2016-11-09 16:11
Also ran into this surprising bug recently. Would love to resolve this somehow.

**Comment by jakirkham** [comment] 2016-11-09 17:02
Looking at the code, I think the issue has to do with selection. In particular, this [line]( https://github.com/h5py/h5py/blob/2.6.0/h5py/_hl/selections.py#L85 ) causes the problem. This can be demonstrated simply as follows.

```python
In [1]: import numpy

In [2]: int([1, 2])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-18ff4f9b52da> in <module>()
----> 1 int([1, 2])

TypeError: int() argument must be a string or a number, not 'list'

In [3]: int([1])
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-3-7c9c44330c2c> in <module>()
----> 1 int([1])

TypeError: int() argument must be a string or a number, not 'list'

In [4]: int(numpy.array([1, 2]))
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-9da7ac2589b6> in <module>()
----> 1 int(numpy.array([1, 2]))

TypeError: only length-1 arrays can be converted to Python scalars

In [5]: int(numpy.array([1]))
Out[5]: 1
```

The last case avoids the `FancySelection` case (potentially relying on this special case behavior). As a result, it goes through a code path that allows this entry to be treated as a simple integer index.

While this is definitely still a bug in `h5py`, it could easily be argued to be a NumPy bug. That being said, a workaround would still be desirable for this case.

**Comment by jakirkham** [comment] 2016-11-09 17:09
Raised issue ( https://github.com/numpy/numpy/issues/8262 ) with `numpy` to see what is going on with these conversions.

**Comment by jakirkham** [comment] 2016-11-09 18:00
It looks like the moral of the story is this isn't a bug, but instead unsupported behavior. Namely `numpy.ndarray`s are not permissible arguments. Only `list`s are permissible. However, the right error message is not raised. Please see issue ( https://github.com/h5py/h5py/issues/431 ) for more details.

**Comment by aragilar** [comment] 2017-12-09 10:13
Closing as duplicate of #431.

**Closed by aragilar** 2017-12-09 10:13 UTC
Labels: duplicate
