### ISSUE TITLE
Casting Group to File type points to wrong attribute location

### ISSUE THREAD

**Issue by QuiteAFoxtrot** [h5py/h5py#1076] opened 2018-08-13 23:23 UTC
OS: Ubuntu 18.04
Python 3.6.5 (Anaconda)
h5py 2.7.1
HDF5 1.10.2

I'm currently using Keras in conjunction with h5py via the built-in Keras save_model utility function, which takes an h5py.File as input and saves the weights of a neural network.  At work, we use a particular format built on HDF5 such that I'd rather save the Keras weights to an h5py.Group instead of an h5py.File.

I tricked Keras into saving to an h5py.Group without any problem by using the following

`
    save_group = my_h5py_file.create_group(some_name)

    class Patch(h5py.File, h5py.Group):
        pass

    save_group.__class__ = Patch

    keras_model.save(save_group)
`

This was actually working fine and dandy for a little while, until I ran into an obscure naming attribute bug.  I investigated and it turns out that the Keras function saves a couple of attributes like 'backend' for instance, on the group I give it (save_group in the snippet above).  However, instead of ending up with an attribute on save_group, it ends up with attributes on the root object, my_h5py_file.

Sooner or later in the keras save_model function, the following happens:
`
save_group.attrs['backend'] = 'tensorflow' #creates my_h5py_file.attrs['backend'] = 'tensorflow' instead
`

I realize that this is quite an obscure use case and my particular problem could be easily fixed by the Keras team allowing the use of an h5py.Group instead of ONLY the h5py.File, but I thought the h5py team here might be interested in this.  Maybe the h5py AttributeManager is doing a bad check or something? Seems like a problem to allow attributes to get written to the wrong group in any case so I thought I'd open the issue.

I hope someone finds this interesting or helpful.

**Comment by tacaswell** [comment] 2018-08-14 20:50
Can you trigger this bug without setting `__class__`?

This is particularly weird because `Group` is a subclass of `File`.

**Comment by QuiteAFoxtrot** [comment] 2018-08-14 21:16
Well, I don't know if I can re-create it without setting __class__, but you can recreate it without the Keras stuff I mentioned.  Something simple like

`
  my_file = h5py.File("temp.h5", 'w')
group1 = my_file.create_group("group1")
class Patch(h5py.File, h5py.Group):
    pass
group1.__class__ = Patch
group1.attrs['moose'] = 'orange'
list(my_file.attrs.keys()) #prints ['moose']
list(group1.attrs.keys()) #also prints ['moose']
`

**Comment by tacaswell** [comment] 2018-08-15 00:49
This behavior makes sense.  The `attrs` property on File looks like https://github.com/h5py/h5py/blob/cae0c01d4d3589cde20fe49fc7df750dfbe94a51/h5py/_hl/files.py#L198-L205

where as the `attrs` on the base object looks like https://github.com/h5py/h5py/blob/cae0c01d4d3589cde20fe49fc7df750dfbe94a51/h5py/_hl/base.py#L267-L272

Your `Patch` is effectively reversing the MRO so it hits the File version before the base version (you could also do `group1.__class__ = h5py.File` and it should have the same effect) which passes the root group into the underlying cython machinery.

The real fix is to get keras to change that File check -> Group, but if you want to keep monkey patching `__class__` you just have to make sure you also (re)override the `attrs` property.

I am going to close this as not a bug as I do not think you can reproduce this with out setting `__class__` which (in my opinion) voids the warranty :stuck_out_tongue_winking_eye: .

**Closed** 2018-08-15 00:50 UTC

**Comment by QuiteAFoxtrot** [comment] 2018-08-15 14:55
Ok thanks for the help @tacaswell !
