### ISSUE TITLE
Error while packaging h5py

### ISSUE THREAD

**Issue by harshithdwivedi** [h5py/h5py#1496] opened 2020-02-16 13:40 UTC
To assist reproducing bugs, please include the following:
 * Operating System: MacOS, 10.9-x86_64
 * Python version: (e.g. 2.7, 3.5) 3.7
 * Where Python was acquired: System
 * h5py version (e.g. 2.6): 2.10.0
 * HDF5 version (e.g. 1.8.17): 1.10.4
 * The full traceback/stack trace shown (if it appears)

```
import h5py
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "h5py/__init__.pyc", line 36, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
SystemError: <method 'load_module' of 'zipimport.zipimporter' objects> returned NULL without setting an error
```

I'm currently packaging an app using tensorflow with py2app and since keras internally uses h5py, upon running the packaged app I'm getting this error.

Any help would be much appreciated, thanks!

**Comment by tacaswell** [comment] 2020-02-16 18:39
I suspect that this should be reported to py2app as this looks like the issue is in the artifact created by py2app not a bug in h5py code.

**Comment by harshithdwivedi** [comment] 2020-02-17 08:31
py2app doesn't have an issue tracker or an official Github repo, so I'm not sure how to go about this :/

**Comment by tacaswell** [comment] 2020-02-18 04:42
Their [docs](https://py2app.readthedocs.io/en/latest/index.html#online-resources) link to https://github.com/ronaldoussoren/py2app/issues .  I would start there and failing that, try their mailing list.

**Comment by harshithdwivedi** [comment] 2020-02-18 06:21
Ah, I might have missed that.
Thanks, I'll do so and report the findings here.

**Comment by tacaswell** [comment] 2020-02-18 16:16
I'm going to close this for now.  Please ping to have re-opened or open a new issue if there is something we can fix on the h5py side.

**Closed by tacaswell** 2020-02-18 16:16 UTC
