### ISSUE TITLE
Use file space management so deleting objects decreases file size

### ISSUE THREAD

**Issue by 1313e** [h5py/h5py#1100] opened 2018-09-25 05:28 UTC
Summary of the h5py configuration
---------------------------------

h5py    2.8.0
HDF5    1.10.2
Python  3.5.5 |Anaconda, Inc.| (default, May 13 2018, 21:12:35) 
[GCC 7.2.0]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.14.3

I have a very simple question/problem that has been bothering me for quite a while now (and it is becoming incredibly annoying): Why, when I delete something (like a group or dataset) inside an HDF5-file, does the size of the HDF5-file stay the same?
I initially thought that it had something to do with HDF5 automatically reserving disk space for the file, and therefore when you delete something from the file, its size stays the same (since that space is still reserved).
However, this would mean that if I write something to the file again, it should use the space that was once being used and is still being reserved, instead of simply increasing the file size.

This does not happen.
If I make a large dataset in an HDF5-file, close the file, open it again, delete the dataset, close the file and keep repeating this process, the file size will keep on increasing even though the actual size should always be the same.

The following script shows the problem:
```
import h5py
import numpy as np

for _ in range(50):
    with h5py.File('test.hdf5', 'a') as file:
        file.create_dataset('test_set', data=np.random.rand(int(1e7)))
    with h5py.File('test.hdf5', 'a') as file:
        del file['test_set']
```
When I execute this script, I see the size of the HDF5-file increasing slowly but surely.

Does anybody have any idea why this is?
Does this have to do with how HDF5 works (and is therefore really hard to solve), or is it something with the h5py implementation?

**Comment by rmvanhees** [comment] 2018-09-25 06:18
Dear Ellert,

This is a HDF5 feature, see
https://support.hdfgroup.org/HDF5/doc/Advanced/FileSpaceManagement/FileSpaceManagement.pdf
If you need more information, then please contact the HDF5 mailinglist.

Best regards,

Richard van Hees

**Comment by tacaswell** [comment] 2018-09-27 01:27
My suspicion is that this is something that needs to be set in the property list used to create the file (from following the typical patterns of hdf5).  I suggest investigating how to configure this through c, then make sure we have enough functions exposed, and then make sure we can thread this through the `File.__init__` method.

**Comment by aparamon** [comment] 2018-10-01 08:27
Hi @1313e !

Please take a look into
https://github.com/h5py/h5py/blob/ae6aa856d3921b294d1f5f69654975f724fedc23/h5py/_hl/files.py#L291
that specifies Property Lists like this:
https://github.com/h5py/h5py/blob/ae6aa856d3921b294d1f5f69654975f724fedc23/h5py/_hl/files.py#L94
(in this case File *Access* Property List, but you are after File *Creation* Property List; anyway those objects have very similar interface).

You'll need to extend
https://github.com/h5py/h5py/blob/ae6aa856d3921b294d1f5f69654975f724fedc23/h5py/h5p.pyx#L277
with
https://support.hdfgroup.org/HDF5/doc/RM/RM_H5P.html#Property-SetFileSpaceStrategy
The latter should be added to
https://github.com/h5py/h5py/blob/master/h5py/api_functions.txt
first.

Please note that only the latter requires *a bit* of C code; everything else is achievable with Cython and Python.

Just follow http://docs.h5py.org/en/latest/contributing.html ,
and good luck!

**Comment by 1313e** [comment] 2018-10-01 09:02
Hi @aparamon.
Thanks for that nice overview, I will have a look at it very soon.
Does indeed look a lot easier than I thought (my C-knowledge should be enough for that).

**Comment by jnsebgosselin** [comment] 2019-02-07 20:37
I think this may be considered as a duplicate of #997. At the very least, both issues are closely related.

I would like to see this feature added to `h5py` as well. Meanwhile, I'm using `h5repack`, but this is not very convenient.

**Comment by tacaswell** [comment] 2019-02-12 05:11
Thanks @jnsebgosselin !

I took the liberty of re-naming this issue to be better representative of the merged issues.

**Comment by takluyver** [comment] 2019-04-25 20:40
Is anyone interested in working on it soon? If not, I'll drop it from the 2.10 milestone.

**Comment by takluyver** [comment] 2019-06-04 10:21
Dropping the milestone because it's not being worked on.

**Comment by aragilar** [comment] 2020-07-31 13:56
I think with the advice that @aparamon gives in https://github.com/h5py/h5py/issues/1100#issuecomment-425827323, someone could try to come up a good first pass at implementing this.

**Comment by dota17** [comment] 2020-08-12 01:35
@aragilar I just found this has been done in #1494.

**Comment by takluyver** [comment] 2020-08-13 09:47
Yup, I agree, it looks like it's done.

**Closed by takluyver** 2020-08-13 09:47 UTC
Labels: good first issue
