### ISSUE TITLE
h5 files not detected in jupyter

### ISSUE THREAD

**Issue by aamouselab** [h5py/h5py#2236] opened 2023-02-19 08:53 UTC
Hi I am a new jupyter user, with limited coding skills. I was using jupyter lab to read some h5 files and plot data using matplotlib, which was working well until matplot randomly stopped plotting graphs.

I tried fixing this in different ways but was unsuccessful. Once I closed all jupyter notebooks and reopened them to load h5 files and read them, I started getting the following error message:

---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
Cell In [3], line 1
----> 1 with h5py.File(filename, "r") as f:
      2     dset_names = list(f.keys())
      3     locations = f["tracks"][:].T

File ~/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py:533, in File.__init__(self, name, mode, driver, libver, userblock_size, swmr, rdcc_nslots, rdcc_nbytes, rdcc_w0, track_order, fs_strategy, fs_persist, fs_threshold, fs_page_size, page_buf_size, min_meta_keep, min_raw_keep, locking, alignment_threshold, alignment_interval, **kwds)
    525     fapl = make_fapl(driver, libver, rdcc_nslots, rdcc_nbytes, rdcc_w0,
    526                      locking, page_buf_size, min_meta_keep, min_raw_keep,
    527                      alignment_threshold=alignment_threshold,
    528                      alignment_interval=alignment_interval,
    529                      **kwds)
    530     fcpl = make_fcpl(track_order=track_order, fs_strategy=fs_strategy,
    531                      fs_persist=fs_persist, fs_threshold=fs_threshold,
    532                      fs_page_size=fs_page_size)
--> 533     fid = make_fid(name, mode, userblock_size, fapl, fcpl, swmr=swmr)
    535 if isinstance(libver, tuple):
    536     self._libver = libver

File ~/opt/anaconda3/lib/python3.9/site-packages/h5py/_hl/files.py:226, in make_fid(name, mode, userblock_size, fapl, fcpl, swmr)
    224     if swmr and swmr_support:
    225         flags |= h5f.ACC_SWMR_READ
--> 226     fid = h5f.open(name, flags, fapl=fapl)
    227 elif mode == 'r+':
    228     fid = h5f.open(name, h5f.ACC_RDWR, fapl=fapl)

File h5py/_objects.pyx:54, in h5py._objects.with_phil.wrapper()

File h5py/_objects.pyx:55, in h5py._objects.with_phil.wrapper()

File h5py/h5f.pyx:106, in h5py.h5f.open()

FileNotFoundError: [Errno 2] Unable to open file (unable to open file: name = 'XXX.analysis.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0).

-------------------------

I have proof that the file is in the directory that I picked.
Anyhow, the urgent fix right now is getting jupyter to read h5 files again. How can I do?

Any piece of advice is most welcome. 

Thank you!

--------------------------

 * Operating System (e.g. Windows 10, MacOS 12.6)
 * Python version (Python 3.9.6)
 * Where Python was acquired (e.g. system Python on MacOS or  Anaconda)
 * h5py version : 
 pip install h5py
Requirement already satisfied: h5py in ./.pyenv/versions/3.10.6/lib/python3.10/site-packages (3.8.0)
Requirement already satisfied: numpy>=1.14.5 in ./.pyenv/versions/3.10.6/lib/python3.10/site-packages (from h5py) (1.24.1)

**Comment by ajelenak** [comment] 2023-02-19 14:49
This is not an h5py problem. The only advice I can think of right now is to check what is the working folder of your Jupyter notebook and whether the value of the `filename` variable is accurate path from the notebook's working folder to the h5 file. I think the `%pwd` magic command in a notebook cell should print the notebook's working folder.

**Comment by aamouselab** [comment] 2023-02-19 19:46
Hi @ajelenak , thank you for your reply! 
Everything is on my desktop. I'm not sure how this changed. Is there a specific command that I can use to change the working directory? I'm new to jupyter and anything coding-related...
I opened a new terminal, did "cd desktop" to access the folder I wanted to and opened a jupyter again. It looks like now it's reading the h5 file again. However, it's not plotting my graphs anymore and I have no idea why or how. I've been using a code the following code, which was working perfectly before but stopped all of a sudden. I now get an empty window with no graph when I do this:

Limb_INDEX = 0

Limb_loc = locations1[:, Limb_INDEX, :, :]

import seaborn as sns
import matplotlib as mpl
import matplotlib.pyplot as plt

sns.set('notebook', 'ticks', font_scale=1.2)
mpl.rcParams['figure.figsize'] = [15,6]
plt.figure()
plt.plot(Limb_loc[:,0,0], 'y',label='Limb')

plt.legend(loc="center right")
plt.title('Limb locations')
plt.legend()

**Comment by ajelenak** [comment] 2023-02-20 15:10
I cannot help with the plotting problem. Your code uses the term "limb" so are you trying to plot some satellite data?  I suggest you search for plotting examples with the same data and start from there.

**Comment by tacaswell** [comment] 2023-02-20 15:44
I am going to close this as it is not a bug in h5py.

For support with Matplotlib I suggest posting questions to https://discourse.matplotlib.org .

**Closed by tacaswell** 2023-02-20 15:44 UTC
