### ISSUE TITLE
h5py 2.8 fails to import

### ISSUE THREAD

**Issue by chrisgmorton** [h5py/h5py#1050] opened 2018-06-05 17:14 UTC
* Operating System Mac OSX 10.13.4
 * Python version 3.6.4, built from source
 * h5py version 2.8, 2.7.1, installed with pip
 * HDF5 version 1.10.1, built from source.

When installing h5py 2.8 with pip I get the following stack trace on import:

```
In [1]: import h5py
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-c9f0b8c65221> in <module>()
----> 1 import h5py

~/usr/tcad/fusion/prod/lib/python3.6/site-packages/h5py/__init__.py in <module>()
     24 # We tried working around this by using "package_dir" but that breaks Cython.
     25 try:
---> 26     from . import _errors
     27 except ImportError:
     28     import os.path as _op

ImportError: dlopen(/Users/chrisgmorton/usr/tcad/fusion/prod/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libhdf5.101.dylib
  Referenced from: /Users/chrisgmorton/usr/tcad/fusion/prod/lib/python3.6/site-packages/h5py/_errors.cpython-36m-darwin.so
  Reason: Incompatible library version: _errors.cpython-36m-darwin.so requires version 103.0.0 or later, but libhdf5.101.dylib provides version 102.0.0
```

Reverting back to h5py 2.7.1, using pip, import and test suite executes perfectly.

**Comment by aragilar** [comment] 2018-06-06 00:40
@chrisgmorton Did you use a wheel to install h5py? This looks like some kind of conflict between the wheel and your installed HDF5.

**Comment by chrisgmorton** [comment] 2018-06-06 00:59
I just did
```
pip3 install h5py 
```
which fails to import.
```
pip3 install h5py==2.7.1
```
works fine.

**Comment by chrisgmorton** [comment] 2018-06-06 02:59
The problem with the --no-binary option is that is builds from source but does not use environment settings I use in my build (I can see clang being referenced when I use gcc-7). I can probably fix these issues by just building from source from a script that configures compilers, DYLD_LIBRARY_PATH for numpy (I use MKL), etc. I'm not sure if your intent was for the wheel install with pip to automatically figure out whether to deploy HDf5 binaries or use those currently installed.

**Comment by aragilar** [comment] 2018-06-06 03:37
The PyPI wheel (assuming it's been built properly) never uses the system HDF5. If you build from source (e.g. via `--no-binary`), then h5py will use whatever compiler settings distutils/setuptools/cython are told to use (so setting CC/CXX/DYLD_LIBRARY_PATH etc. should do what you want).

**Comment by chrisgmorton** [comment] 2018-06-06 03:54
I tried building from source but
```
python3 setup.py build --hdf5=$HDF5ROOT
```
did not locate the correct HDF5 libraries even though this shell variable seems  to be set correctly. 
This variable points to a location where there is a /lib directory containing
```
libhdf5.101.dylib	libhdf5.dylib		libhdf5.la		libhdf5.settings	libhdf5_hl.100.dylib	libhdf5_hl.dylib	libhdf5_hl.la
```
I get Path to HDF5: None.

**Comment by aragilar** [comment] 2018-06-06 12:17
@chrisgmorton It looks like the mac wheels (on py36 at least) are missing HDF5, which would be the cause of your problems. I'd suggest building from source for now.

@matthew-brett @ngoldbaum This looks like something went wrong in the wheel builder. It probably makes sense to discuss this on https://github.com/MacPython/h5py-wheels/pull/5/

**Comment by aragilar** [comment] 2018-06-06 12:37
@matthew-brett @ngoldbaum Apologies, I didn't click that the dylibs were in a hidden folder (so missed the files when listing them). Any idea what could be causing this (the MacOS version looks recent, could that be a problem?)

**Comment by matthew-brett** [comment] 2018-06-06 15:17
I just installed the wheel on my laptop, macOS 10.13.4, Python 3.6.5 from Homebrew, it imports fine:

```
$ python -c 'import h5py'
```

The wheel ships with `libhdf5.101.dylib`, this provides compatibility version 103.0.0:

```
$ otool -L .dylibs/libhdf5.101.dylib 
.dylibs/libhdf5.101.dylib:
	/DLC/h5py/libhdf5.101.dylib (compatibility version 103.0.0, current version 103.0.0)
	@loader_path/libsz.2.dylib (compatibility version 3.0.0, current version 3.1.0)
	@loader_path/libaec.0.dylib (compatibility version 1.0.0, current version 1.4.0)
	/usr/lib/libz.1.dylib (compatibility version 1.0.0, current version 1.2.8)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.60.2)
```

I wonder whether you (@chrisgmorton) have another libhdf5 earlier on your runtime discovery path, that it is finding instead.   Have you got anything in `$DYLD_LIBRARY_PATH`?

**Comment by chrisgmorton** [comment] 2018-06-06 16:43
Yes, I have an installation of HDF5 1.10.1 that is built from source and deployed into a customer install location. My startup script sets DYLD_LIBRARY_PATH to find the lib location.

**Comment by matthew-brett** [comment] 2018-06-06 16:52
I would bet pretty strongly that, if you unset DYLD_LIBRARY_PATH, the pip-installed h5py wheel will work correctly.

**Comment by chrisgmorton** [comment] 2018-06-06 17:00
You are probably right but DYLD_LIBRARY_PATH has to be set for my application. With h5py 2.7.1 I was able to install with pip and have h5py find my HDF5 libraries. I'm not sure if 2.8 is the first time the h5py wheel has included an HDF5 distribution. If this is the case that's a good thing as building any base applications from source is time consuming and error prone for the masses. If there's now way to install the wheel and have h5py use a custom install of HDF5 then I'll revert to building from source which is a good trade-off for the masses. It may be possible in future for me to remove my HDF5 build and just revert to using that bundled with the h5py wheel (if this is what is currently happening which I assume it must be from the above).

**Comment by chrisgmorton** [comment] 2018-06-06 18:34
I presume just building/installing the latest version of HDF5 would also resolve this issue.

**Comment by tacaswell** [comment] 2018-06-12 05:40
I am inclined to close this as not a bug. 

https://github.com/h5py/h5py/pull/1054 documents the hdf5 version the wheels are built against.

**Closed** 2018-07-14 11:00 UTC
Labels: no-action-taken
