### ISSUE TITLE
Change in dtype returned in h5py v2.10.0

### ISSUE THREAD

**Issue by ivirshup** [h5py/h5py#1307] opened 2019-09-16 04:27 UTC
Using *nix operating systems on python 3.6 and 3.7, the dtype of fixed length ascii strings stored in compound dtypes changed from h5py `v2.9` to `v2.10`.

Here's a small example, writing using `v2.9` (though it doesn't seem to matter which I've written with):

```python
import h5py
import numpy as np
import pandas as pd

d = pd.DataFrame({"a": [b"abc", b"def"]})
with h5py.File("test.h5", "a") as f:
    f["x"] = d.to_records(column_dtypes={"a": "S3"})
```

Now reading. Here's the code used:

```python
import h5py
with h5py.File("test.h5", "r") as f:
    print(f["x"].dtype.descr)
```

Reading with h5py `v2.9` prints:

```
[('index', '<i8'), ('a', '|S3')]
```

`v2.10`:

```
[('index', '<i8'), ('a', ('|S3', {'h5py_encoding': 'ascii'}))]
```

It's very possible this is intentional, and was done for good reasons. It is a change in behavior though, and I think should at least documented be in the change notes.

**Comment by tacaswell** [comment] 2019-09-17 08:03
This came in via https://github.com/h5py/h5py/pull/1132 .

It looks like tacking some meta-data into the dtype, but it is still the same type.  Is this breaking anything?

**Comment by ivirshup** [comment] 2019-09-17 08:21
It did break some stuff here: https://github.com/theislab/scanpy/issues/832, though that code is being replaced. It also broke the replacement a bit https://github.com/theislab/anndata/issues/215, but we've worked around that now.

I'm using `h5py.Dataset.dtype.descr` to figure out how to decode a compound dtype with special dtypes. Is there a more "blessed" way to do this?

**Comment by tacaswell** [comment] 2019-09-17 10:04
I'm sorry this broke you, but I don't think this is a regression in h5py.

From the docs of `descr` (
https://docs.scipy.org/doc/numpy/reference/generated/numpy.dtype.descr.html#numpy.dtype.descr) it looks like that is meant to be an internal representation and interestingly, the descr of the sub-type depends on if it is being used in a compound datatype:

```
In [96]: dt.descr
Out[98]: [('index', '<i8'), ('a', ('|S3', {'h5py_encoding': 'ascii'}))]

In [99]: dt['a'].descr
Out[99]: [('', '|S3')]

In [100]: dt
Out[100]: dtype([('index', '<i8'), ('a', 'S3')])
```

This probably should be reported to numpy, however, rather than backing the information you want out of `desc`, you should do something like

```
new_dt = [((name, 'U{}'.format(sdt.itemsize//4)) if sdt.kind == 'S' else sdt)
          for name, (sdt, _) in dt.fields.items()]
```

Do you have a simple example of the issue behind https://github.com/theislab/anndata/issues/215 ?  That one worries me much more.

**Comment by ivirshup** [comment] 2019-09-17 10:55
https://github.com/theislab/anndata/issues/215 was caused by the second element of a `descr` entry for fixed-length strings being a tuple in h5py 2.10.0. I'd been using that to sniff vlen string dtypes before. I've been doing this since `h5py.check_dtype` didn't seem straightforward to use on fields of a compound dtype.

https://github.com/theislab/scanpy/issues/832 is the one I know less about. It would probably take some doing for me to figure it out.

There's a little bit more on the `descr` field [here](https://docs.scipy.org/doc/numpy/reference/arrays.interface.html).

**Comment by tacaswell** [comment] 2019-09-17 12:18
I think the list comprehension in my last post will fix theislab/scanpy#832 , but it looks like that code is no longer there on the master branch.

I think what is going is is that because the second entry is a tuple not a string, the second indexing _works_ but fails the equality test in the ternary and then we hit

> Warning: This attribute exists specifically for `__array_interface__`, and is not a datatype description compatible with np.dtype.

where the values in `descr` can not be passed back into `np.dtype` (hence the very odd error).

**Comment by tacaswell** [comment] 2019-09-17 13:39
It looks like numpy also does not do this right (see https://github.com/numpy/numpy/issues/14142) :stuck_out_tongue_winking_eye: .

**Comment by takluyver** [comment] 2020-11-03 10:03
Closing as I don't think there's anything to be fixed in h5py. Sorry the change broke stuff.

**Closed by takluyver** 2020-11-03 10:03 UTC
