### ISSUE TITLE
Runtime exception combining netCDF4 1.5.3 with h5py 2.9.0 or later

### ISSUE THREAD

**Issue by medlin01GA** [h5py/h5py#1541] opened 2020-05-01 08:22 UTC
Both h5py 2.9.0 and 2.10.0 reproduce this error when used with netCDF4 Python package version 1.5.3. The error disappears when either the h5py version is downgraded or the netCDF4 Python version is downgraded. The error I am getting is:

```
Traceback (most recent call last):
File "test_netCDF4.py", line 18, in <module>
  test_main()
File "test_netCDF4.py", line 12, in test_main
  x[:] = val
File "netCDF4/_netCDF4.pyx", line 4950, in netCDF4._netCDF4.Variable.setitem
File "netCDF4/_netCDF4.pyx", line 5229, in netCDF4._netCDF4.Variable._put
File "netCDF4/_netCDF4.pyx", line 1887, in netCDF4._netCDF4._ensure_nc_success
RuntimeError: NetCDF: HDF error
```

I managed to whittle it down to a very minimal piece of code to reproduce the error:

```python
# This works for h5py==2.8.0 + netCDF4==1.5.3, OR with h5py==2.9.0 (or later) and netCDF4==1.5.2,
# but not with h5py==2.9.0 (or later) and netCDF4==1.5.3

import h5py  # For h5py 2.9.0 or 2.10.0, comment this line to fix, or move it after netCDF4 import
from netCDF4 import Dataset

def test_main():
    root_grp = Dataset('result.nc', 'w', format='NETCDF4')
    root_grp.createDimension('dummy', 1)  # comment this line to fix
    x = root_grp.createVariable('x', 'f4')
    val = 1.0
    x[:] = val
    root_grp.close()

if __name__ == '__main__':
    print(h5py.version.info)
    test_main()
```

As noted in the code snippet above, the exception disappears if any of the following modifications are made:
- move the h5py import *AFTER* the netCDF4 import
- comment the line that creates the dimension field in the root group
- drop h5py version back to 2.8.0
- drop netCDF4 version back to 1.5.2

I have replicated this bug on CentOS 6 and Ubuntu 18.04.4 LTS.

Details for the Ubuntu environment:

> Operating System: Ubuntu 18.04.4 LTS
> Kernel: Linux 4.15.0-99-generic
> Architecture: x86-64

Python versions tested: 3.6.2 and 3.6.9, both system CPython Python 3 distros in running in virtualenv.

Version information printed out by my sample code shows HDF5 version 1.10.4:

> Summary of the h5py configuration
> h5py    2.9.0
> HDF5    1.10.4
> Python  3.6.9 (default, Apr 18 2020, 01:56:04)
> [GCC 8.4.0]
> sys.platform    linux
> sys.maxsize     9223372036854775807
> numpy   1.18.3

The expected result is the following (produced using h5dump):

```
HDF5 "expected_result.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
            STRSIZE 34;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
      DATASPACE  SCALAR
      DATA {
      (0): "version=2,netcdf=4.6.3,hdf5=1.10.4"
      }
   }
   DATASET "dummy" {
      DATATYPE  H5T_IEEE_F32BE
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): 0
      }
      ATTRIBUTE "CLASS" {
         DATATYPE  H5T_STRING {
               STRSIZE 16;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
         DATASPACE  SCALAR
         DATA {
         (0): "DIMENSION_SCALE"
         }
      }
      ATTRIBUTE "NAME" {
         DATATYPE  H5T_STRING {
               STRSIZE 64;
               STRPAD H5T_STR_NULLTERM;
               CSET H5T_CSET_ASCII;
               CTYPE H5T_C_S1;
            }
         DATASPACE  SCALAR
         DATA {
         (0): "This is a netCDF dimension but not a netCDF variable.         1"
         }
      }
      ATTRIBUTE "_Netcdf4Dimid" {
         DATATYPE  H5T_STD_I32LE
         DATASPACE  SCALAR
         DATA {
         (0): 0
         }
      }
   }
   DATASET "x" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SCALAR
      DATA {
      (0): 1
      }
   }
}
}
```

The actual result up to the point of crashing is as follows:

```
HDF5 "result.nc" {
GROUP "/" {
   ATTRIBUTE "_NCProperties" {
      DATATYPE  H5T_STRING {
            STRSIZE 34;
            STRPAD H5T_STR_NULLTERM;
            CSET H5T_CSET_ASCII;
            CTYPE H5T_C_S1;
         }
      DATASPACE  SCALAR
      DATA {
      (0): "version=2,netcdf=4.6.3,hdf5=1.10.4"
      }
   }
   DATASET "dummy" {
      DATATYPE  H5T_IEEE_F32BE
      DATASPACE  SIMPLE { ( 1 ) / ( 1 ) }
      DATA {
      (0): 0
      }
   }
   DATASET "x" {
      DATATYPE  H5T_IEEE_F32LE
      DATASPACE  SCALAR
      DATA {
      (0): 9.96921e+36
      }
   }
}
}
```

**Comment by takluyver** [comment] 2020-06-05 15:31
Did you install either netCDF4 or h5py as wheels using pip?

Wheels are very convenient to avoid needing to compile packages, but in order to work independently of your system, non-Python dependencies like hdf5 need to be bundled inside the wheel. But this can go wrong when different packages bundle the same library, and I suspect you're running into this.

If I'm right about that, then there are a few ways to avoid the problem:

- Install both packages from source ([h5py instructions](http://docs.h5py.org/en/stable/build.html#source-installation)) so they are built with the same HDF5 library
- Install them both with a more comprehensive package manager, such as conda, which can also install hdf5
- Avoid using them in the same process - e.g. if you mainly use netCDF4, run a subprocess when you need to do something with h5py. Or have long-lived processes sending each other messages. This does add extra complexity, though, so it's a last resort.

**Comment by takluyver** [comment] 2020-07-31 15:25
In the absence of other evidence, I'm assuming that the packaging issue I described above is the cause, so I'm going to close this. If that is it, I'm not aware of anything we can do about it.

**Closed by takluyver** 2020-07-31 15:25 UTC
