### ISSUE TITLE
Fail to update structured/composite datatype

### ISSUE THREAD

**Issue by sboeser** [h5py/h5py#770] opened 2016-11-01 15:53 UTC
In a HDF5-file with a dataset of a structured/composite datatype, updating a field of the structured datatype will fail silently, i.e. the data is not updated and no error is generated.

Here is an example. I create the datafile like this:

    df = h5py.File("dummy.hdf","w")
    data = np.zeros_like(range(10),dtype=np.dtype([('a','f4'),('b','f4')]))
    df.create_dataset("test",data=data)
    df.close()

Trying to update the dataset using assignment to a slice of it ***fails silently***, but all values are still zeros:

    df = h5py.File("dummy.hdf","r+")
    df['test']['a'][0:5] = range(5)
    print df['test'][:]

I would have expected at least a warning, but actually I think throwing an error would be the right thing if the assignment can't be made.

The only way I found to update the datasets is to create a **copy** of the **whole** dataset (pretty bad idea in my actual application), update the slice in the copied `numpy.array` and reassign that `array` to the original dataset.

    data = np.copy(df['test'])
    data['a'][0:5] = range(5)
    df['test'][:] = data
    print df['test'][:]
 
This is h5py 2.6.0 in a Jupyter 4.2.3 notebook running an 2.7.10 kernel with Numpy 1.11.2

**Comment by aragilar** [comment] 2017-12-18 04:02
This is a duplicate of #740. See it for more details.

**Closed by aragilar** 2017-12-18 04:02 UTC
