### ISSUE TITLE
h5py.highlevel not imported in 2.8

### ISSUE THREAD

**Issue by cdeil** [h5py/h5py#1046] opened 2018-05-29 15:11 UTC
This issue is triggered by this fail:
https://travis-ci.org/gammapy/gammapy/jobs/382758346#L3846

It looks like what happened was that h5py 2.8 was tagged 16 days ago:
https://github.com/h5py/h5py/releases/tag/2.8.0

It seems that it's not on PyPI yet: #1040

But for some reason it was released via conda-forge:
https://github.com/conda-forge/h5py-feedstock/pull/30/files

This is confusing, the source release should come first, no?

Also, I'm not sure why that triggered the error. Shouldn't `h5py.highlevel.File` still be present in 2.8?

**Comment by aragilar** [comment] 2018-05-30 00:39
`h5py.highlevel` should still exist, but it's been deprecated for a while (so I'm not sure what's happening with your tests...). Before it was deprecated, everything in `h5py.highlevel` was imported into top-level `h5py`, so there should be no problems with older versions of h5py. I wasn't aware of the conda-forge update, but presumably conda-forge watches tags rather than PyPI.

**Comment by bsipocz** [comment] 2018-05-31 13:28
@aragilar - The github url is given in the conda-forge recipe rather than the usual pypi one. I don't know whether there was a reason for it or it's just accidental.

**Comment by cdeil** [comment] 2018-06-01 08:56
@tacaswell - Can you please comment here?

It looks like you released `h5py` 2.8 via https://github.com/conda-forge/h5py-feedstock/pull/30/files#diff-e178b687b10a71a3348107ae3154e44cR1 on conda, and for some reason `import h5py.highlevel` is failing there and this is causing problems for Astropy users (see https://github.com/astropy/astropy/pull/7509). I don't understand what's going on, at least `h5py/highlevel.py` is still there.

**Comment by aragilar** [comment] 2018-06-01 12:00
Ok, I bisected the code to find the bug (if you look carefully, the issue isn't importing `h5py.highlevel`, but importing `h5py` and then trying to access `h5py.highlevel`), and git says https://github.com/h5py/h5py/commit/629ae24f2cf0eaed4367a5f5da6bc3ddaad14ed3#diff-85236946a38a02073b6801911832bf97 is the problem, though I have no idea why. Below is the script I used to find this.

```sh
#!/bin/sh

set -e

ENV_NAME=test_env
virtualenv --python `which python3` "$ENV_NAME"
"$ENV_NAME/bin/python" -m pip install .
cd "$ENV_NAME"
bin/python -c "import h5py;h5py.highlevel"
cd -
rm -r "$ENV_NAME"
```

**Comment by cdeil** [comment] 2018-06-01 13:20
@aragilar - Sorry for being imprecise, and thank you for finding the issue.

I see at
https://github.com/h5py/h5py/commit/629ae24f2cf0eaed4367a5f5da6bc3ddaad14ed3#diff-85236946a38a02073b6801911832bf97L67
the line
```
from .tests import run_tests
```
was removed from `h5py/__init__.py`, and in `h5py/tests/__init__.py` I see imports that look like they triggered the import of `h5py.highlevel`.

So I think this change lead to `import h5py` no longer importing `h5py.highlevel`, whereas previously it did.

Now what to do?
I guess adding `import highlevel` to `h5py/__init__.py` is one option that would revert the regression.
Another option could be to just close this issue as won't fix, given that `h5py.highlevel` has been deprecated for a long time.
You could also emit a deprecation warning from there, if you ever plan to remove it.
This would have let us notice the issue with using deprecated code from Astropy.

**Comment by aragilar** [comment] 2018-06-01 14:09
#1047 adds deprecation warnings where needed.

We could do a bugfix release with the additional import, but I'm not sure it's worth it. I'm surprised astropy didn't just import `h5py.highlevel` (I didn't realise if a submodule is imported, it gets added to the module as per https://docs.python.org/3/reference/import.html#submodules), which wouldn't have had any problems, is it common that people use submodules without importing them (if it is, then maybe we should do a bugfix then)?

**Comment by cdeil** [comment] 2018-06-01 14:52
> is it common that people use submodules without importing them (if it is, then maybe we should do a bugfix then)?

It's not very common, but also not unheard of. I think the most prominent example is that people do `import os` and then access `os.path`. This works because in `os.py` they import `os.path`:
https://github.com/python/cpython/blob/1381bfe9776e64fed45935efbe42a7ee8298bd44/Lib/os.py#L57
So Astropy might be the only example, or more likely there's more code out there using `h5py.highlevel` that did that and I'm just the first one to complain.

> We could do a bugfix release with the additional import, but I'm not sure it's worth it.

Well, as an Astropy user, this would be my preferred option of course, if it's not too much work for you.
I think it would mean that you'd have to add
```
import highlevel
```
to `h5py/__init__.py` to revert that aspect of #1014 by @t20100 .
Note that this would mean that #1047 can't be merged now, but only in a year or two when the `import highlevel` from  `h5py/__init__.py` is removed.

**Comment by rainwoodman** [comment] 2018-06-01 19:54
The shortcut name highlevel was in the public API, and the 2.8.0 release didn't announce its removal. 

Therefore I recommend adding the shortcut back to the h5py module in a bugfix release of 2.8.x.

The removal of the entire highlevel module from the public API, including the shortcut name, can be deferred to 2.9.0, where a proper process can be followed?

**Comment by aragilar** [comment] 2018-06-05 13:19
#1047 now has a module wrapper for `h5py.highlevel` (not the best, but it should be sufficient for this purpose). Do people want to check if that fixes the astropy breakage?

**Comment by aragilar** [comment] 2018-06-05 13:22
FYI, I've updated the bug title to make things more clear.

**Comment by tacaswell** [comment] 2018-06-12 05:33
I'm leaning towards @cdeil 's suggestion of just putting the import back and delaying the deprecation until 2.9.  We hit 2 big projects (astropy and cellprofiler) which makes me worry we are going to hit a lot of other projects (ex https://github.com/search?l=Python&p=2&q=h5py.highlevel&type=Code)

**Comment by takluyver** [comment] 2018-10-16 12:12
On the other hand, it's now four months later, and there was no 2.8.1 hotfix release. So any project affected by this has probably now worked around it. It sounds like it's easy to fix downstream code to `import h5py.highlevel`. We're working towards 2.9 soon, so I'd lean towards closing it,

**Comment by tacaswell** [comment] 2018-10-16 14:01
Closed by https://github.com/h5py/h5py/pull/1047 as well.

**Closed by tacaswell** 2018-10-16 14:01 UTC
Labels: bug, bug-in-external-lib
