### ISSUE TITLE
Error using h5r>init h5py.h5r (line 145) AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by RomanFoell** [h5py/h5py#1151] opened 2018-12-31 15:54 UTC
* Operating System Windows 7 enterprise
 * Python version 3.6.7 Anaconda installation
 * Matlab 9.1.0.441655 (R2016b)
pyversion 'C:\ProgramData\Anaconda3\envs\tensorflow\python.exe'
... = py.importlib.import_module('file_name'); 
 * h5py version 2.9.0
 * HDF5 version 1.10.4

Hello,

I want to use tensorflow via matlab as above.
I can import tensorflow and h5py both without any problems in the console.
When I want to use it together with matlab I get the error:

```
Error: Python Error: AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'
init h5py.h5r at 145
init h5py._conv at 21
<module> at 36
<module> at 38
<module> at 39
<module> at 43
<module> at 22
<module> at 35
<module> at 24
<module> at 24
<module> at 88
<module> at 24
<module> at 2
_call_with_frames_removed at 219
exec_module at 678
_load_unlocked at 665
_find_and_load_unlocked at 955
_find_and_load at 971
_gcd_import at 994
import_module at 126
Error using h5r>init h5py.h5r (line 145)
Python Error: AttributeError: type object 'h5py.h5r.Reference' has no attribute
'__reduce_cython__'

Error in h5r>init h5py._conv (line 21)

Error in __init__><module> (line 36)
from ._conv import register_converters as _register_converters

Error in saving><module> (line 38)
  import h5py

Error in network><module> (line 39)
from tensorflow.python.keras.engine import saving

Error in training><module> (line 43)
from tensorflow.python.keras.engine.network import Network

Error in multi_gpu_utils><module> (line 22)
from tensorflow.python.keras.engine.training import Model

Error in __init__><module> (line 35)
from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model

Error in activations><module> (line 24)
from tensorflow.python.keras.utils.generic_utils import deserialize_keras_object

Error in __init__><module> (line 24)
from tensorflow.python.keras import activations

Error in __init__><module> (line 88)
from tensorflow.python import keras

Error in __init__><module> (line 24)
from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import

Error in demo_regression_UCI><module> (line 2)
import tensorflow as tf

Error in <frozen importlib>_call_with_frames_removed (line 219)

Error in <frozen importlib>exec_module (line 678)

Error in <frozen importlib>_load_unlocked (line 665)

Error in <frozen importlib>_find_and_load_unlocked (line 955)

Error in <frozen importlib>_find_and_load (line 971)

Error in <frozen importlib>_gcd_import (line 994)

Error in __init__>import_module (line 126)
    return _bootstrap._gcd_import(name[level:], package, level)

Error in Deep_GP_Doubly_Model/modelfit (line 181)
obj.loadPythonModule();
```

Can you help me with this?
Do you know what is the problem?

Thanks.

**Comment by RomanFoell** [comment] 2019-01-06 11:54
* Operating System Windows 7 enterprise
 * Python version 3.6.8 Anaconda installation
 * Matlab 9.1.0.441655 (R2016b)
pyversion 'C:\ProgramData\Anaconda3\envs\tensorflow\python.exe'
... = py.importlib.import_module('file_name');
 * tensorflow version 1.12.0
 * gpflow version 1.3.0
 * h5py version 2.9.0
 * HDF5 version 1.10.4

Hello,

I tried a little bit around, to get closer to what went wrong.
I did reinstall of Anaconda3 python before.

In the 'C:\ProgramData\Anaconda3\envs\test\Lib\site-packages\h5py'

there are files from the env installation named

'.....cp36-win_amd64.pyd'

where ... are the file-names in the 'h5py' folder, when I download it from here:

(I call them raw files)
h5py/h5r.pyx
h5py/h5r.pyd
h5py/....pyx
h5py/....pyd

When I completely replace these '.....cp36-win_amd64.pyd' files with the raw file from here,
tensorflow can be imported via matlab without errors.

But now, I also want to import gpflow and there I get first an error:

```
Error using __init__><module> (line 26)
Python Error: ImportError: cannot import name '_errors'

Error in saver><module> (line 18)
import h5py

Error in __init__><module> (line 16)
from .saver import Saver

Error in __init__><module> (line 56)
from .saver import Saver

Error in demo_regression_UCI><module> (line 8)
from gpflow.likelihoods import Gaussian
```

which is strange, because there is a try: line.

Well now I again just replaced '_errors.pxd' and '_errors.pyx' with '_errors.cp36-win_amd64.pyd' and i get through this error, but a new one says:

```
Error using __init__><module> (line 36)
Python Error: ModuleNotFoundError: No module named 'h5py._conv'

Error in saver><module> (line 18)
import h5py

Error in __init__><module> (line 16)
from .saver import Saver

Error in __init__><module> (line 56)
from .saver import Saver

Error in demo_regression_UCI><module> (line 8)
from gpflow.likelihoods import Gaussian
```

So I also replaced '_conv.pxd' and '_conv.pyx' with '_conv.cp36-win_amd64.pyd' and i get again thorugh this error, but now it wants:

```
Error using h5r>init h5py._conv (line 21)
Python Error: ModuleNotFoundError: No module named 'h5py.h5r'

Error in __init__><module> (line 36)
from ._conv import register_converters as _register_converters

Error in saver><module> (line 18)
import h5py

Error in __init__><module> (line 16)
from .saver import Saver

Error in __init__><module> (line 56)
from .saver import Saver

Error in demo_regression_UCI><module> (line 8)
from gpflow.likelihoods import Gaussian
```

So I replace 'h5r.pyx' and 'h5r.pyd' with 'h5r.cp36-win_amd64.pyd' and I get stock by the same error in my first post above.

Somehow tensorflow works with the raw files from here, but gpflow does not.

I also tried it in the console and the raw files work for the import of tensorflow, but not for gpflow.
When I add these three files as above and try to import tensorflow, gpflow, h5py from the console seperately, I get the error:
```

import tensorflow (gpflow) (h5py )
...
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\__
init__.py", line 24, in <module>
    from tensorflow.python import test# pylint: disable=unused-im
port
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\__init__.py", line 88, in <module>
    from tensorflow.python import keras
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\__init__.py", line 24, in <module>
    from tensorflow.python.keras import activations
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\activations.py", line 24, in <module>
    from tensorflow.python.keras.utils.generic_utils import deserialize_keras_ob
ject
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\utils\__init__.py", line 35, in <module>
    from tensorflow.python.keras.utils.multi_gpu_utils import multi_gpu_model
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\utils\multi_gpu_utils.py", line 22, in <module>
    from tensorflow.python.keras.engine.training import Model
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\engine\training.py", line 43, in <module>
    from tensorflow.python.keras.engine.network import Network
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\engine\network.py", line 39, in <module>
    from tensorflow.python.keras.engine import saving
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\tensorflow\py
thon\keras\engine\saving.py", line 38, in <module>
    import h5py
  File "C:\ProgramData\Anaconda3\envs\test\lib\site-packages\h5py\__init__
.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py\h5r.pxd", line 21, in init h5py._conv
  File "h5py\h5r.pyx", line 145, in init h5py.h5r
AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'

```

Thanks for your help.

**Comment by RomanFoell** [comment] 2019-01-09 14:58
Thanks for your readings until now. I got around this by just not importing h5py everywhere, seems to work for me. I would be still interested in the type of error I made.

**Comment by fengye92** [comment] 2019-01-14 07:50
> Thanks for your readings until now. I got around this by just not importing h5py everywhere, seems to work for me. I would be still interested in the type of error I made.

I met this problem, too. I would like to call tensorflow via matlab, but these is also the 'h5py error' when 'import tensorflow as tf'. Have you resolved this problem now? 
Thanks.

**Comment by tacaswell** [comment] 2019-01-14 15:31
This should be reported against anaconda, Matlab, or tensorflow.

I strongly suspect that this is a compilation, installation, or linking issue.  Unless you can reproduce this issue without tensorflow or MATLAB, I do not think this is an h5py bug.

I am going to close this, but please ping to have re-opened it is reproducible using just python + h5py.

**Closed by tacaswell** 2019-01-14 15:31 UTC

**Comment by jonaskrause** [comment] 2019-02-26 20:46
Not sure why this is closed, I'm having the same problem and no answer so far.

**Comment by robisen1** [comment] 2019-05-31 02:56
The main issue seems to be around what version of h5py you are using. This is how I dealt with the issue https://robipsen.wordpress.com/2019/05/31/dealing-with-attributeerror-type-object-h5py-h5r-reference-has-no-attribute-__reduce_cython__/

**Comment by PeterJPRoche** [comment] 2019-06-10 22:33
I had h5py-2.9.0 installed and got this issue. Followed @robisen1 suggestion and installed 2.8.0
conda install h5py=2.8.0
Fixed the problem for me

**Comment by gauravkoradiya** [comment] 2019-06-17 12:15
> conda install h5py=2.8.0

nice....my issue resolved

**Comment by robisen1** [comment] 2019-06-18 22:58
glad my pain helped someone :-) very annoying issue that

**Comment by Michael-VT** [comment] 2019-08-12 18:42
conda install h5py==2.8.0 // in Anacoda3
pip install h5py==2.8.0     // in Windows 10
Fixed the problem for me

**Comment by Deltaidiots** [comment] 2019-08-28 10:33
> > Thanks for your readings until now. I got around this by just not importing h5py everywhere, seems to work for me. I would be still interested in the type of error I made.
> 
> I met this problem, too. I would like to call tensorflow via matlab, but these is also the 'h5py error' when 'import tensorflow as tf'. Have you resolved this problem now?
> Thanks.

Have you find the solution to this problem from matlab ? same is happening with me

**Comment by khodabakhshih** [comment] 2020-02-22 13:25
@PeterJPRoche , @robisen1 @Michael-VT god bless you. it solved my issue too

**Comment by Johan-Karlsson** [comment] 2020-03-17 16:09
@robisen1 @PeterJPRoche @Michael-VT @khodabakhshih Did you successfully import tensorflow and h5py in matlab using this solution? If so, what version of python and tensorflow did you use? And what matlab version?

**Comment by Johan-Karlsson** [comment] 2020-03-17 16:17
I'm basically trying to run: 
py.importlib.import_module('h5py')

But I get the following error:
Error using h5r>init h5py.h5r (line 145)
Python Error: AttributeError: type object 'h5py.h5r.Reference' has no attribute '__reduce_cython__'

**Comment by robisen1** [comment] 2020-03-26 00:12
> @robisen1 @PeterJPRoche @Michael-VT @khodabakhshih Did you successfully import tensorflow and h5py in matlab using this solution? If so, what version of python and tensorflow did you use? And what matlab version?

Sorry I missed this. If i recall correctly it was Tensorflow 2 and Keras 2. I dont remember exact config.
  If you really need me to find it I have it as a anaconda environment somewhere. The version of python 3.6.8 since tensorflow and keras dont seems to like anything about 3.6.

**Comment by robisen1** [comment] 2020-03-26 00:12
> I'm basically trying to run:
> py.importlib.import_module('h5py')
> 
> But I get the following error:
> Error using h5r>init h5py.h5r (line 145)
> Python Error: AttributeError: type object 'h5py.h5r.Reference' has no attribute '**reduce_cython**'

what is your config for your environment. thats the exact issue I ran into

**Comment by Johan-Karlsson** [comment] 2020-03-26 06:45
@robisen1 I didn't solve this problem, but I found a way around it. I simply uninstalled h5py from my environment and then used pickle to save stuff instead of the .h5-format. Anyway, thanks for answering!

**Comment by robisen1** [comment] 2020-03-26 19:15
Glad to hear.
