### ISSUE TITLE
close h5py file twice

### ISSUE THREAD

**Issue by sunqm** [h5py/h5py#847] opened 2017-02-10 17:53 UTC
Hi,

An error is raised if close function is called twice.
ValueError: Not a file id (Not a file id)

It'd be better to raise a warning than an error here.

Qiming

**Comment by tacaswell** [comment] 2017-02-10 22:27
@sunqm Can you provide a minimal example to reproduce this issue?

In general I am against warnings, they are either ignored by people or greatly annoy people.

Closing seems like something that should just silently no-op if the file is already closed.

**Comment by sunqm** [comment] 2017-02-10 23:31
f = h5py.File('abc')
f.close()
f.close()

ValueError: Not a file id (Not a file id)

This is h5py 2.6.0 from anaconda2.

**Comment by aragilar** [comment] 2017-02-11 02:23
From the full traceback, we can see the error is due to close trying to access the already closed file. A simple fix should be to check if the file is closed before trying to close the associated objects (which the file should have closed), but I want to check that won't cause some kind of leak before I'd call it fixed.

Traceback (most recent call last):
  File "<input>", line 1, in <module>
    f.close()
  File "/home/aragilar/.virtualenvs/tmp-6ec200324fd6974a/lib/python3.5/site-packages/h5py/_hl/files.py", line 287, in close
    id_list = h5f.get_obj_ids(self.id, ~h5f.OBJ_FILE)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/tmp/pip-build-2u2qhvha/h5py/h5py/_objects.c:2846)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/tmp/pip-build-2u2qhvha/h5py/h5py/_objects.c:2804)
  File "h5py/h5f.pyx", line 230, in h5py.h5f.get_obj_ids (/tmp/pip-build-2u2qhvha/h5py/h5py/h5f.c:3433)
ValueError: Not a file id (Not a file id)

**Comment by vasole** [comment] 2017-02-13 09:54
@sunqm @tacaswell 

It is not that I like it, but it seems Python behavior is to effectively ignore the second close as the code below shows:

```
a = open("dummy.out", "w")
a.write("something")
a.close()
a.close()
```

**Closed** 2017-04-20 18:39 UTC
