### ISSUE TITLE
Support multidimensional shape with vlen

### ISSUE THREAD

**Issue by aron-bordin** [h5py/h5py#943] opened 2017-10-28 05:15 UTC
Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  3.6.2 (default, Jul 20 2017, 03:52:27) 
[GCC 7.1.1 20170630]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.13.3

I'm trying to use the special_dtype within a multidimensional array, but it's not working.

```
        dt = h5py.special_dtype(vlen=np.dtype('int32'))
        docs = self.h5.create_dataset('docs', shape=(1000, 2), dtype=dt)

        for i in range(1000):
            docs[i][0] = list(range(i))
            docs[i][1] = list(range(i))
```

The output file have a fixed size (192.8Kb). However, if I use a 1D shape it works.

**Comment by aragilar** [comment] 2017-12-09 11:57
Duplicate of #876.

**Closed by aragilar** 2017-12-09 11:57 UTC
Labels: duplicate
