### ISSUE TITLE
AttributeError on import when building from source

### ISSUE THREAD

**Issue by hameerabbasi** [h5py/h5py#1237] opened 2019-06-14 17:39 UTC
To assist reproducing bugs, please include the following:
 * Operating System: macOS 10.14
 * Python version: 3.7.2
 * Where Python was acquired: Anaconda
 * h5py version (e.g. 2.6): f5463ad632510a39bd04f895a60784985c8ddbfa
 * HDF5 version (e.g. 1.8.17): 1.10
 * The full traceback/stack trace shown (if it appears):

```
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/hameerabbasi/Quansight/h5py/h5py/__init__.py", line 49, in <module>
    from ._hl.files import (
  File "/Users/hameerabbasi/Quansight/h5py/h5py/_hl/files.py", line 41, in <module>
    libver_dict.update({'v108': h5f.LIBVER_V18, 'v110': h5f.LIBVER_V110})
AttributeError: module 'h5py.h5f' has no attribute 'LIBVER_V18'
```

**Comment by tacaswell** [comment] 2019-06-15 04:08
can you run a `git clean -xfd` and try re-building?

**Comment by hameerabbasi** [comment] 2019-06-15 07:05
I already did that, I forgot to mention that in the issue description. But, I just double-checked and it does happen.

**Comment by hameerabbasi** [comment] 2019-06-15 07:48
As an update: Removing and re-creating my conda environment has no effect.

**Comment by tacaswell** [comment] 2019-06-15 16:51
I can not reproduce this locally (and CI is passing so we can not reproduce it their either).  How are you installing h5py?  From the paths it looks like `pip install -e .`?  Did you ever do a `pip install --user` or have a conda also installed version of h5py giving you out-of-date files?

**Comment by hameerabbasi** [comment] 2019-06-15 16:55
I'm doing the following:

```
conda create -n h5py-dev python=3 numpy pytest hdf5 pkg-config
conda activate h5py-dev
pip install -e .
```

**Comment by hameerabbasi** [comment] 2019-06-15 16:57
`--user` is redundant in `conda`, nevertheless, I did follow your instructions and it still didn't work.

**Comment by tacaswell** [comment] 2019-06-15 17:07
Try not doing editable and remember to `git clean -xfd`.

Following your instructions exactly I get a much worse issue:

```
jupiter@13:03  ➤  python
Python 3.7.3 (default, Mar 27 2019, 22:11:17) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import h5py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/tcaswell/source/bnl/h5py/h5py/__init__.py", line 36, in <module>
    from ._conv import register_converters as _register_converters
  File "h5py/h5r.pxd", line 21, in init h5py._conv
  File "h5py/_objects.pxd", line 12, in init h5py.h5r
  File "h5py/_objects.pyx", line 1, in init h5py._objects
ImportError: /home/tcaswell/source/bnl/h5py/h5py/defs.cpython-37m-x86_64-linux-gnu.so: undefined symbol: H5Ovisit_by_name

```

which I suspect means the build process could see my system hdf5...

**Comment by tacaswell** [comment] 2019-06-15 17:38
Ah, this makes sense, do you have hdf5 1.8 installed at the system level?

If I do

```
python setup.py configure --hdf5=/home/tcaswell/.virtualenvs/h5py-dev/
python setup.py install
```

it works.  Something is going wrong with the auto-discovery during the build and it is linking against the system at build time, but then finding the conda-supplied libraries at run time.  I suspect that this is packaging issue on the anaconda side as pkg-config does not seem to be working correctly:

```
(h5py-dev) ✔  ~
jupiter@13:18  ➤  pkg-config --list-all | grep hdf
hdf5_hl_cpp-1.10.5                         hdf5_hl_cpp - HDF5 (Hierarchical Data Format 5) Software Library
hdf5_cpp-1.10.5                            hdf5_cpp - HDF5 (Hierarchical Data Format 5) Software Library
hdf5-1.10.5                                hdf5 - HDF5 (Hierarchical Data Format 5) Software Library
hdf5_hl-1.10.5                             hdf5_hl - HDF5 (Hierarchical Data Format 5) Software Library
(h5py-dev) ✔  ~
jupiter@13:18  ➤  which pkg-config
/home/tcaswell/.virtualenvs/h5py-dev/bin/pkg-config
(h5py-dev) ✔  ~
jupiter@13:18  ➤  conda list | grep hdf
hdf5                      1.10.4               hb1b8bf9_0    defaults
libgcc-ng                 9.1.0                hdf63c60_0    defaults
libgfortran-ng            7.3.0                hdf63c60_0    defaults
libstdcxx-ng              9.1.0                hdf63c60_0    defaults
(h5py-dev) ✔  ~
jupiter@13:20  ➤  
```

If you throw a -v on to the install command you should see something like:

```
    Autodetected HDF5 1.10.4
    ********************************************************************************
                           Summary of the h5py configuration

        Path to HDF5: None
        HDF5 Version: '1.10.4'
         MPI Enabled: False
    Rebuild Required: True

    ********************************************************************************

```

If I remove `hdf5` from the conda enviroment it uniformly sees the system hdf5 and imports cleanly.

`pip install --no-build-isolation .` does not help when conda's hdf5 is installed.

**Comment by takluyver** [comment] 2019-06-16 10:54
I've also had problems building from source in a conda environment when hdf5 is installed both in the conda environment and systemwide. I had assumed this was some consequence of my somewhat unusual setup (lots of `--user` installed packages), so I figured out some hackish workaround and forgot about it. But if it's a problem that affects other people, I'd be interested in figuring it out better.

conda-forge currently passes an explicit hdf5 path when building it, rather than relying on `pkgconfig` to detect HDF5:

https://github.com/conda-forge/h5py-feedstock/blob/bab6953586416d4f173701c9bec248d86b230087/recipe/build.sh#L8

**Comment by takluyver** [comment] 2019-06-16 10:59
When I do `pkg-config --list-all | grep hdf` in my conda environment, nothing comes up, even though hdf5 1.10.4 is installed there.

**Comment by hameerabbasi** [comment] 2019-06-16 10:59
I checked, and I don’t believe I have a system wide installation. Not in `brew` anyway, which is the only package manager I have installed. And I didn’t install it via a package or similar either.

**Comment by takluyver** [comment] 2019-06-16 11:31
I've been investigating this and getting more confused. On my Fedora system, neither the system installation nor a conda installation appear to include an `hdf5.pc` file to describe it to `pkg-config`, yet it seems to detect it anyway. Maybe the .pc file is only needed if it's in a location other than the default?

@hameerabbasi do you have any hdf5-related files in `/usr/local/lib` or `/opt/local/lib`? The configure script specifically looks in those two locations.

**Comment by takluyver** [comment] 2019-06-16 14:58
If you do have `.pc` files relating to hdf5, I think it will make a difference whether `pkg-config` is installed in your conda environment or not, because it will search different directories. This is separate from the `pkgconfig` package (which is a Python wrapper around `pkg-config`).

You can check where pkg-config is installed with:

```
which pkg-config
```

And see which directories it searches by default with:

```
pkg-config --variable pc_path pkg-config
```

(This list of directories can also be extended by the `PKG_CONFIG_PATH` environment variable).

**Comment by takluyver** [comment] 2019-06-16 15:25
There is already code to warn if it has found a different version from the one against which it was built:

https://github.com/h5py/h5py/blob/af02bcadd5e76b75990c893b17215fcb8ec2d875/h5py/__init__.py#L74-L79

But in both of the failing examples above, it hits another error before this check can run. Maybe we should try moving it nearer the top of `__init__.py` so there's more chance of getting the helpful warning message before such errors.

**Comment by hameerabbasi** [comment] 2019-06-17 05:50
```
$ which pkg-config
/Users/hameerabbasi/anaconda/envs/h5py-dev/bin/pkg-config
$ pkg-config --list-all | grep hdf
$ ls /usr/local/lib/ | grep hdf
$ ls /opt/local/lib/ | grep hdf
$ conda list | grep hdf5
hdf5                      1.10.4               hfa1e0ec_0
```

So (probably) the version detection is broken.

```
﻿﻿    ********************************************************************************
                           Summary of the h5py configuration

        Path to HDF5: None
        HDF5 Version: '1.8.4'
         MPI Enabled: False
    Rebuild Required: True

    ********************************************************************************
```

**Comment by hameerabbasi** [comment] 2019-06-17 06:00
With #1239, I get: `Loading library to get version: libhdf5.so`

**Comment by hameerabbasi** [comment] 2019-06-17 06:09
I think the path detection is hardcoded to `libhdf5.so`... If we use `*.dylib` instead it may work:

```
ls -l | grep hdf5
-rwxrwxr-x    1 hameerabbasi  staff   3492832 Jun 15 09:47 libhdf5.103.dylib
-rw-rw-r--    1 hameerabbasi  staff   5590152 Jun 15 09:47 libhdf5.a
lrwxr-xr-x    1 hameerabbasi  staff        17 Jun 15 09:47 libhdf5.dylib -> libhdf5.103.dylib
-rw-rw-r--    1 hameerabbasi  staff      4783 Jun 15 09:47 libhdf5.settings
-rwxrwxr-x    1 hameerabbasi  staff    484232 Jun 15 09:47 libhdf5_cpp.103.dylib
-rw-rw-r--    4 hameerabbasi  staff    749912 Dec 19 20:36 libhdf5_cpp.a
lrwxr-xr-x    1 hameerabbasi  staff        21 Jun 15 09:47 libhdf5_cpp.dylib -> libhdf5_cpp.103.dylib
-rw-rw-r--    4 hameerabbasi  staff    395512 Dec 19 20:36 libhdf5_fortran.a
-rwxrwxr-x    1 hameerabbasi  staff    128336 Jun 15 09:47 libhdf5_hl.100.dylib
-rw-rw-r--    4 hameerabbasi  staff    166376 Dec 19 20:36 libhdf5_hl.a
lrwxr-xr-x    1 hameerabbasi  staff        20 Jun 15 09:47 libhdf5_hl.dylib -> libhdf5_hl.100.dylib
-rwxrwxr-x    1 hameerabbasi  staff     21436 Jun 15 09:47 libhdf5_hl_cpp.100.dylib
-rw-rw-r--    4 hameerabbasi  staff     12368 Dec 19 20:36 libhdf5_hl_cpp.a
lrwxr-xr-x    1 hameerabbasi  staff        24 Jun 15 09:47 libhdf5_hl_cpp.dylib -> libhdf5_hl_cpp.100.dylib
-rw-rw-r--    4 hameerabbasi  staff    167552 Dec 19 20:36 libhdf5hl_fortran.a
```

**Comment by aragilar** [comment] 2019-06-17 07:02
Having a fallback version seems to cause more trouble than it's worth (https://github.com/h5py/h5py/blob/master/setup_configure.py#L163), see #855 and the "HDF5 library version mismatched error" bugs which disappear once things are cleaned up (there's probably more where having the fallback made it harder to debug). We should probably straight up fail the build, and inform the user to use `HDF5_DIR` and/or `HDF5_VERSION`.

**Comment by takluyver** [comment] 2019-06-17 07:03
Thanks for diving in, I think #1240 looks promising.

I wonder if we should also remove the exception catching around `autodetect_version`, so that if it fails to find libhdf5 it aborts rather than assuming it's got version 1.8.4:

https://github.com/h5py/h5py/blob/af02bcadd5e76b75990c893b17215fcb8ec2d875/setup_configure.py#L160-L165

**Comment by aragilar** [comment] 2019-06-17 07:09
@takluyver Exactly ;)

**Comment by takluyver** [comment] 2019-06-17 07:14
#1241 would drop that try/except.

**Comment by takluyver** [comment] 2019-06-17 07:21
@aragilar - I see you added the check for mismatched build & run HDF5 versions in #867. Do you see any issue with moving that nearer the start of `__init__.py` so it runs before various other modules are imported and potentially trigger errors?

**Comment by aragilar** [comment] 2019-06-17 07:37
No, that seems fine to me (the only cython code being loaded is h5.pyx, which is loaded first anyway).

**Comment by hameerabbasi** [comment] 2019-06-17 10:13
> I wonder if we should also remove the exception catching around autodetect_version, so that if it fails to find libhdf5 it aborts rather than assuming it's got version 1.8.4:

I agree with this, except for the "also" part. Although a combination of the two things was a cause for the issue, the wrong fallback path, if corrected, helps rather than deters.

**Comment by takluyver** [comment] 2019-06-17 10:45
@hameerabbasi: sorry, I'm not quite following your last comment. Do you think we shouldn't do #1241? Or that we should do something different?

**Comment by hameerabbasi** [comment] 2019-06-17 10:47
To be concrete: I think we should remove the fallback for version, but correct the fallback for the shared library to be OS-dependent. I can do that in #1241 if needed.

**Comment by takluyver** [comment] 2019-06-17 11:24
So #1240 (correcting the fallback shared library name) + #1241 (removing the version number fallback)? I think we can just merge both PRs, assuming the other maintainers don't object. They shouldn't conflict.

**Comment by hameerabbasi** [comment] 2019-06-17 13:05
Just merging both is fine by me too. 😄

**Closed** 2019-06-17 14:13 UTC
