### ISSUE TITLE
infinite loop when closing file

### ISSUE THREAD

**Issue by jreadey** [h5py/h5py#556] opened 2015-04-02 21:23 UTC
I'm getting an "infinite loop closing library" error when using libver="latest".

See example below.  Without the libver='latest' the file closes fine, but the entire script takes some time to run (~8 seconds on my system).  With the libver="latest' it's much faster (~0.2 seconds), but I get the infinite loop message.

This is with h5py 2.4 and hdf5 lib 1.8.14.

```
import h5py
import time

ATTR_COUNT = 1000
f = h5py.File("attr1k.h5", "w", libver='latest')

create_start = time.time()
print "creating attributes", create_start
# create attributes
for i in range(ATTR_COUNT):
    name = 'a{:04d}'.format(i)
    f.attrs[name] = "this is attribute: " + str(i)

modify_start = time.time()
print "updating attributes", modify_start

# modify
for i in range(ATTR_COUNT):
    name = 'a{:04d}'.format(i)
    f.attrs[name] = "an updated attribute: " + str(i)

modify_end = time.time();
print "done!", modify_end
print "total time: ", (modify_end - create_start)

f.close()
```

**Comment by andrewcollette** [comment] 2015-04-03 18:44
Could you post the error message?  Btw, this may be an HDF5 problem... all the libver keyword does is set a flag on the file access property list.

**Comment by jreadey** [comment] 2015-04-09 18:10
Here's the error message:

```
HDF5: infinite loop closing library
      D,G,A,S,T,F,FD,P,PL,FD,P,FD,P,E,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL
```

Strangely I don't see the error on my Mac, but only with Linux.

The equivalent C program doesn't produce an error:
```

#include "hdf5.h"

#include <stdio.h>
#include <string.h>

#define ATTR_COUNT 1000

void main(int argc, char** argv)
{
  hid_t file, fapl, dtype, dspace, attr;
  int i;
  char *wdata[1], name[80];

  wdata[0] = name;

  fapl = H5Pcreate(H5P_FILE_ACCESS);
  H5Pset_libver_bounds(fapl, H5F_LIBVER_LATEST, H5F_LIBVER_LATEST);

  file = H5Fcreate("attr1k.h5", H5F_ACC_TRUNC, H5P_DEFAULT, fapl);

  dtype = H5Tcopy(H5T_C_S1);
  H5Tset_size(dtype, H5T_VARIABLE);
  dspace = H5Screate(H5S_SCALAR);

  printf("creating attributes\n");
  for (i = 0; i < ATTR_COUNT; ++i)
    {
      sprintf(name, "a:%04d", i);
      attr = H5Acreate2(file, name, dtype, dspace, H5P_DEFAULT, H5P_DEFAULT);
      sprintf(name, "this is attribute: %d", i);
      H5Awrite(attr, dtype, &wdata);
      H5Aclose(attr);
    }

  printf("updating attributes\n");
  for (i = 0; i < ATTR_COUNT; ++i)
    {
      sprintf(name, "a:%04d", i);
      attr = H5Aopen(file, name, H5P_DEFAULT);
      sprintf(name, "an updated attribute: %d", i);
      H5Awrite(attr, dtype, &wdata);
      H5Aclose(attr);
    }

  H5Sclose(dspace);
  H5Tclose(dtype);
  H5Fclose(file);
}
```

Is it possible that libver is exposing some issue on the h5py side?

**Comment by andrewcollette** [comment] 2015-04-13 13:15
Maybe, but I can't think where.  Once that value goes into the property list we don't touch it any more.  I'll leave this issue open but I'm stumped.

**Comment by jreadey** [comment] 2015-04-14 22:01
Is there some way that h5py can generate a trace of the HDF5 lib calls?  If we had that the hdf5 library development team could take a look.

**Comment by andrewcollette** [comment] 2015-04-15 18:48
Not that I know of.  You could try running Python in verbose mode, though (python -v).

**Comment by chissg** [comment] 2016-07-29 12:11
The below example is sufficient to reproduce the problem with h5py-2.6.0. The difference between triggering the problem and not (apart from the aforementioned libver='latest') is the number of attributes: 544 will trigger, 543 will not. The threshold would appear to be the triggering of "dense" attributes as supported in HDF5 1.8 and above. The example below was tested with HDF 1.10.0-patch1.

```
import h5py
f = h5py.File("test.h5", "w", libver="latest")
dset = f.create_dataset("test", shape=(1000,))
dset[:] = 2.6
for counter in xrange(1,544):
    name = "{}".format(counter)
    rref = dset.regionref[5:40]
    dset.attrs[name] = rref
f.close()
```

**Comment by chissg** [comment] 2016-07-29 16:00
Apparently the magic number shifted after a reboot, it appears not to be a hard number. In my post-reboot checks, 549 is now the number needed to trigger the problem on my OS X Yosemite MacBook Pro; YMMV.

**Comment by derobins** [comment] 2016-07-29 18:58
I see this failure with numbers as low as 50 and it appears that the failure is random but becomes more likely as the number of attributes increases.

**Comment by subiol** [comment] 2017-03-10 13:54
I am seeing the same bug appear randomly, have not found a pattern. This is the error I get:

> CHDF5: infinite loop closing library
>D,G,S,T,F,FD,P,PL,FD,P,FD,P,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E,E

Has anyone looked into this?

**Comment by tacaswell** [comment] 2017-07-28 15:07
I wonder if this is fixed by the gc fencing in #903

**Comment by tacaswell** [comment] 2017-07-28 15:11
I also can not reproduce this with py3.6, h5py 2.7, hdf5 1.8.18 (event with 100000 attributes).

**Comment by jreadey** [comment] 2017-07-28 15:52
I get this error periodically when h5serv (https://github.com/HDFGroup/h5serv) shuts down.  I've talked about this with the hdf5 library team, but we haven't been able to isolate the issue.

At least it doesn't seem to have any adverse effects.

**Comment by project-tuva** [comment] 2018-09-26 14:31
Hi all, I've written a simple python module to manage r/w from/to hdf5 files and I'm experiencing the same issue. I have Ubuntu 16.04.4 LTS and h5 version 1.10.2.

It seems to be more frequent when attributes were added to a dataset or when the dataset hasn't been already present before launching `make`.

Here the repo: [git@github.com:project-tuva/h5bug.git](url)
There are two branches: `master` and `buggy`. You can run a minimal example by issuing `make`, after having modified the variables in the makefile according to your environment.

It seems that a solution was found for this bug:
[](https://github.com/IntelLabs/hpat/issues/2#issuecomment-360593489)

How can I get rid of this error?

Thanks in advance

**Comment by tacaswell** [comment] 2019-03-12 02:52
I can reproduce this with h5py 2.9 and hdf5 1.10.4 (from arch packages), but with a different error pattern.  I do not think this is in closing the file, but it tearing down the library.   Using a slightly simpler script:

```python
import h5py
import time

ATTR_COUNT = 600
f = h5py.File("attr1k.h5", "w", libver='latest')

create_start = time.time()
print("creating attributes", create_start)
# create attributes
for i in range(ATTR_COUNT):
    name = 'a{:04d}'.format(i)
    f.attrs[name] = "this is attribute: " + str(i)

f.close()
print('closed file?!')
print('about to tear things down')

```

```
creating attributes 1552357400.43879
closed file?!
about to tear things down
HDF5: infinite loop closing library
      L,T_top,P,P,Z,FD,E,SL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL,FL


```

However it does not fail _every_ time which suggests to me there is a race condition in de-allocating the guts of hdf5 and the python side.  With smaller numbers of attributes you still see this, just at lower rates (from eye-balling it) and as reported above by @derobins and @chissg 

This may be fixed by / related to https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/commits/f808c108ed0315f115a7c69cbd8ee95032a64b34 which looks like it got merged to the 1.10 branch in https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/commits/489f6fb69711ef7f26f4c13ad863438779f654b8 which is post 1.10.4 and pre 1.10.5 (I think? I am a bit confusedby the tagging scheme) .

Unfortunately I'm out of bandwidth to build 1.10.5 locally to test this tonight.

**Comment by rmvanhees** [comment] 2019-03-12 07:54
Thomas, I have tried your script with h5py 2.9, hdf5 1.10.5, with the same
result.
The problem is gone when I remove libver='latest'.
I also noticed that the size of the created file is smaller when HDF5
complains.
Has someone already tested this calling the hdf5 library directly?

Greetings, Richard

**Comment by tacaswell** [comment] 2019-03-12 11:11
That does suggest that it is related to the 'dense' attribute storage, but unfortunate that just upgrading won't fix it :(

**Comment by buaacarzp** [comment] 2019-04-29 07:36
Hey， man, its my honer to ask this question, this problem means your h5py file is not be saved completly ,you can try again ,use anothor model to train your  data.

**Comment by epourmal** [comment] 2019-09-19 09:27
Please check your program with the latest HDF5 develop and 1_10 branches.

**Comment by tacaswell** [comment] 2019-09-19 12:26
I can not reproduce this with h5py 2.10 and hdf5 1.10.5.  Clasing as fixed upstream, thanks @epourmal !

**Closed by tacaswell** 2019-09-19 12:26 UTC
Labels: bug, bug-in-external-lib
