### ISSUE TITLE
store a list of strings using create_dataset() in Python3 

### ISSUE THREAD

**Issue by jan-janssen** [h5py/h5py#792] opened 2016-12-06 13:18 UTC
Following the documentation http://docs.h5py.org/en/latest/strings.html  - I am able to store single strings like so: 
```
with h5py.File('test.h5') as h5file: 
    single_str = np.str('foobar')
    h5file.create_dataset('test', data=single_str)
```

Now I want to store a list of strings 
```
with h5py.File('test.h5') as h5file: 
    lst_of_str = [np.str('foo'), np.str('bar')]
    h5file.create_dataset('test', data=lst_of_str)
```

I get the following error message: 
`TypeError: No conversion path for dtype: dtype('<U3')`

The same code is working fine with Python2 but it is not working with Python3.

**Comment by kwotuveang3k4bk** [comment] 2016-12-06 13:50
I guess the issue is related to the datatypes. Strings receive dtype = object for both Python2 and Python3 while the list of strings is '|S3' for Python2 and '<U3' for Python3. 

In line 97 in https://github.com/h5py/h5py/blob/master/h5py/_hl/dataset.py

**Comment by andreabedini** [comment] 2016-12-07 02:16
just commenting to say that the code above is not equivalent between PY2 and PY3. To have the same behaviour in PY3 as in PY2 do `lst_of_str = [b'foo', b'bar']`. Getting string encodings to work consistently with h5py/HDF5 is another problem.

**Comment by aragilar** [comment] 2017-12-09 11:46
Duplicate of #624.

**Closed by aragilar** 2017-12-09 11:46 UTC
Labels: duplicate
