### ISSUE TITLE
VLEN string problem on Win64

### ISSUE THREAD

**Issue by andrewcollette** [h5py/h5py#593] opened 2015-06-30 15:08 UTC
From this thread:

https://groups.google.com/forum/#!topic/h5py/nF_EkdOpCd8

Evidently storing a variable-length string causes a segmentation fault with 2.5.0, on win64 (conda).

**Comment by rossant** [comment] 2015-07-03 09:34
it seems like i have exactly the same problem with booleans. fixed by casting to an int

**Comment by groutr** [comment] 2015-07-07 19:44
I'm pretty sure this is related.
https://github.com/PyTables/PyTables/issues/471

**Comment by cpcloud** [comment] 2015-07-07 22:00
This isn't limited to variable length string dtypes:

```
In [1]: import numpy as np

In [2]: import h5py

In [3]: f = h5py.File('foo.h5')

In [4]: ds = f.create_dataset('/x', shape=(20, 24), dtype=np.dtype([('a', 'i4'), ('b', 'i4')]), chunks=(4, 6))

In [5]: ds
Out[5]:  # crashes the interpreter
```

**Comment by cgohlke** [comment] 2015-07-08 20:57
I can't reproduce these crashes with the builds from http://www.lfd.uci.edu/~gohlke/pythonlibs/#h5py
```
>>> import numpy as np
>>> import h5py
>>> f = h5py.File('foo.h5')
>>> ds = f.create_dataset('/x', shape=(20, 24), dtype=np.dtype([('a', 'i4'), ('b', 'i4')]), chunks=(4, 6))
>>> ds
<HDF5 dataset "x": shape (20, 24), type "|V8">
```

**Comment by groutr** [comment] 2015-07-10 23:02
I can confirm that Python 3.4 on Windows 32bit does not seem to be affected by this issue.

**Comment by rossant** [comment] 2015-07-10 23:10
is this a conda-only problem?

**Comment by groutr** [comment] 2015-07-10 23:16
I don't know if it is a conda only problem.  As far as I can tell, we are compiling hdf5 and h5py correctly.
From what I'm seeing, the difference is the conda packages is linking against the latest hdf5 library (1.8.15patch1).  Is there a change between 1.8.14 and 1.8.15patch1 that might have affected h5py?

When using hdf5 1.8.15patch and h5py 2.5.0, the interpreter crashes running the test suite.  When using hdf5 1.8.14 and h5py 2.5.0, the test suite passes.

**Comment by cgohlke** [comment] 2015-07-11 00:11
I rebuilt against `HDF5 1.8.15-patch1`: No crashes.

**Comment by groutr** [comment] 2015-07-11 13:30
Hmmm....Maybe it is just affecting the conda builds.  I'll look over things again today.

**Comment by groutr** [comment] 2015-07-31 05:59
I'm wondering if threadsafe in hdf5 has anything to do with this.  @cgohlke, are you compiling your hdf5 windows binaries with `HDF5_ENABLE_THREADSAFE`?

**Comment by cgohlke** [comment] 2015-07-31 06:06
`HDF5_ENABLE_THREADSAFE`? No, not for h5py and pytables.

**Comment by subhacom** [comment] 2015-08-22 00:11
I am facing what seems to be the same issue, but for reading dataset containing strings. I cloned master and used setuptools to install on both conda and cygwin. Occurs only with conda, not with cygwin on the same (windows 7) system.

**Comment by jdreaver** [comment] 2015-09-10 21:25
I am experiencing the same issue. If I set an attribute using a string, I get a segfault. It is fixed if I wrap the string in an array: 

```python
group.attrs["key"] = np.array(["string"], dtype=np.string_)
```

However, I think we can agree that this is a bug and this workaround is a band-aid. I am also using the latest `h5py` and `hdf5` packages from conda on Windows 64 bit.

**Comment by jdreaver** [comment] 2015-09-23 22:48
I'll add that I'm also getting a segfault with boolean attributes. (My workaround is to just store them as ints and then restore to bool when loading.)

**Comment by eegroopm** [comment] 2015-09-24 13:27
I can confirm the the issue with variable length strings. jdreaver's workaround also seems to work, albeit only with dtype=np.string_. Trying to use h5py's special dtypes, e.g., dt = h5py.special_dtype(vlen=str), from the documentation still ends with a segfault.

**Comment by jpiersol** [comment] 2015-11-05 21:55
This seems to be fixed in the latest Win64 Anaconda release (Anaconda 2.4.0/Python 3.5).

**Comment by jdreaver** [comment] 2015-11-05 22:06
Thanks for the heads up @jpiersol!

**Closed** 2016-02-10 03:44 UTC
Labels: no-action-taken

**Comment by samerafach** [comment] 2017-02-09 10:23
We are facing exactly the same symptoms with Python 3.5 64-bit and h5py 2.6. A `create_dataset` command without a list wrapping the dataset name crashes the interpreter. Also we tried `h5py.run_tests()` and it works fine.
