### ISSUE TITLE
`RuntimeError: Can't rename attribute (record is already in B-tree)` when building against HDF5 1.10.5

### ISSUE THREAD

**Issue by ArchangeGabriel** [h5py/h5py#1185] opened 2019-03-17 12:02 UTC
To assist reproducing bugs, please include the following:
 * Operating System: ArchLinux
 * Python version: 3.7
 * Where Python was acquired: system Python
 * h5py version: 2.9
 * HDF5 version: 1.10.5
 * The full traceback/stack trace shown:
```
running test
running build_py
running build_ext
Autodetected HDF5 1.10.5
********************************************************************************
                       Summary of the h5py configuration

    Path to HDF5: None
    HDF5 Version: '1.10.5'
     MPI Enabled: False
Rebuild Required: False

********************************************************************************
Executing cythonize()
...........E...........................................x........................................................................x....................................s/build/python-h5py/src/h5py-2.9.0/build/lib.linux-x86_64-3.7/h5py/_hl/files.py:258: H5pyDeprecationWarning: File.fid has been deprecated. Use File.id instead.
  "Use File.id instead.", H5pyDeprecationWarning)
...s......ss.......................................................................................................ssssss.....................................................................x....x.........................x......x..................................................ssss............................................................
======================================================================
ERROR: test_track_order (h5py.tests.old.test_attrs.TestTrackOrder)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/build/python-h5py/src/h5py-2.9.0/build/lib.linux-x86_64-3.7/h5py/tests/old/test_attrs.py", line 180, in test_track_order
    attrs = self.fill_attrs(track_order=True)  # creation order
  File "/build/python-h5py/src/h5py-2.9.0/build/lib.linux-x86_64-3.7/h5py/tests/old/test_attrs.py", line 174, in fill_attrs
    attrs[str(i)] = i
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    with _phil:
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    return func(*args, **kwds)
  File "/build/python-h5py/src/h5py-2.9.0/build/lib.linux-x86_64-3.7/h5py/_hl/attrs.py", line 95, in __setitem__
    self.create(name, data=value, dtype=base.guess_dtype(value))
  File "/build/python-h5py/src/h5py-2.9.0/build/lib.linux-x86_64-3.7/h5py/_hl/attrs.py", line 210, in create
    h5a.rename(self._id, self._e(tempname), self._e(name))
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
    with _phil:
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
    return func(*args, **kwds)
  File "h5py/h5a.pyx", line 118, in h5py.h5a.rename
    H5Arename_by_name(loc.id, obj_name, name, new_name, pdefault(lapl))
RuntimeError: Can't rename attribute (record is already in B-tree)

----------------------------------------------------------------------
Ran 509 tests in 1.536s

FAILED (errors=1, skipped=14, expected failures=6)
```
This is not happening with HDF5 1.10.4 on exactly the same system.

**Comment by epourmal** [comment] 2019-03-17 16:38
Hello!

We have a similar issue reported against 1.10.3 known issue [HDFFV-10579](https://jira.hdfgroup.org/browse/HDFFV-10579). It is still open. We will try to address it in 1.12.0 (May 2019) and then in 1.10.6 (November 2019), If you could [submit](https://help.hdfgroup.org) a C equivalent of your failing Python script it will be extremely helpful.

Thank you!
Elena

**Comment by ArchangeGabriel** [comment] 2019-03-17 16:50
@epourmal Are you asking me or h5py devs? Just in case this wasn’t clear, this is an issue about building h5py, not something from me.

**Comment by epourmal** [comment] 2019-03-17 17:02
Good question :-) 

I am asking h5py community to work with The HDF Group to resolve the issue that causes build failure if the issue is different from the already reported one.

**Comment by tacaswell** [comment] 2019-03-17 21:03
I am going to close this as a duplicate of #1180 see #1186 for a work around (not really a fix, but it gets us back to the same state with 1.10.5 that we were at with 1.10.4). @ArchangeGabriel you may want to apply that patch to the arch builds.

**Closed by tacaswell** 2019-03-17 21:03 UTC

**Comment by ArchangeGabriel** [comment] 2019-03-17 21:41
Don’t know how I missed that other one, despite searching for the error in issues… *cough*

Anyway, thanks, I will indeed pull this patch in our packages.

**Comment by kmuehlbauer** [comment] 2023-01-12 07:53
See upstream https://github.com/HDFGroup/hdf5/issues/1388 for details.
