### ISSUE TITLE
2 KB remained in h5 file after deleting a dataset

### ISSUE THREAD

**Issue by StarostinV** [h5py/h5py#1555] opened 2020-05-22 15:18 UTC
```python
import os
import h5py

with h5py.File('test.h5', 'w'):
    pass

print(os.path.getsize('test.h5'))  # 800 bytes

with h5py.File('test.h5', 'a') as f:
    f.create_dataset('test', data=0)

with h5py.File('test.h5', 'a') as f:
    del f['test']

print(os.path.getsize('test.h5'))  # 2848 bytes

for _ in range(10):
    with h5py.File('test.h5', 'a') as f:
        f.create_dataset('test', data=0)

    with h5py.File('test.h5', 'a') as f:
        del f['test']

print(os.path.getsize('test.h5'))  # 23328 bytes
```

Tested on Windows 10 + Python 3.8.2 and Ubuntu 18.04.4 LTS + Python 3.7.3

* h5py version: 2.10.0
* HDF5 version: 1.10.5

**Comment by tacaswell** [comment] 2020-05-22 16:34
This is an un-avoidable aspect of how hdf5 works.  The data is not stored contiguously and it will not "shrink wrap" when data is removed.  If it did reduce the file size when you deleted a data set you could get very pathological behavior if in a very large (order TB) sized file you deleted a dataset that happened to be encoded near the front.  Instead of a quick operation you would then have to pay both the read and write costs to "shift" the unchanged data.

If you want to re-pack hdf5 files to reclaim empty space, I suggest using `h5repack` https://support.hdfgroup.org/HDF5/doc/RM/Tools.html#Tools-Repack which will do that copy (but hopefully only once!)

I am going to close this because it is the expected behavior of the underlying library.

**Closed by tacaswell** 2020-05-22 16:34 UTC

**Comment by StarostinV** [comment] 2020-05-22 22:05
Thank you for the explanation!
