### ISSUE TITLE
Future warning numpy

### ISSUE THREAD

**Issue by tdegeus** [h5py/h5py#974] opened 2018-01-08 14:04 UTC
* MacOS 10.13.2
 * Python 3.6.4
 * Homebrew

```bash
python3 -c 'import h5py; print(h5py.version.info)'

/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters

Summary of the h5py configuration
---------------------------------

h5py    2.7.1
HDF5    1.8.18
Python  3.6.4 (default, Jan  6 2018, 11:51:59)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]
sys.platform    darwin
sys.maxsize     9223372036854775807
numpy   1.14.0
```

Please take not of the displayed warning:

```bash
/usr/local/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
```

I am not aware about the implications.

**Comment by aragilar** [comment] 2018-01-09 05:31
This will be fixed by #926 (and is a duplicate of #961).

This isn't an issue yet (as numpy hasn't made the breaking change), so you can ignore this.

**Closed by aragilar** 2018-01-09 05:31 UTC
Labels: duplicate

**Comment by dantejauregui** [comment] 2018-01-23 10:54
But how will solve this warning, Aragilar? Is not clear in the other closed tickets

**Comment by aragilar** [comment] 2018-01-23 23:44
@dantejauregui See https://github.com/h5py/h5py/pull/926/files#diff-8772c046830cdff9853033004d8836b3R287, which is the fix.

**Comment by neonb88** [comment] 2018-01-30 04:36
@aragilar Sorry, I'm a total noob.  How do we use that?  Do we pull from that page?

**Comment by aragilar** [comment] 2018-01-30 05:00
@neonb88 You can ignore the warning, it's not going to cause any issues at the moment, but you should upgrade to the next release of h5py when it becomes available.

**Comment by neonb88** [comment] 2018-01-30 15:54
@aragilar Thanks; noted.

**Comment by carljunepiao** [comment] 2018-01-30 20:49
Sorry for the noob question:

How can we upgrade h5py?

**Comment by ashishmalgawa** [comment] 2018-03-17 09:50
Its march and still they haven't fixed the issue :/

**Comment by drorata** [comment] 2018-03-21 08:15
@ArsalanRaza Can you install it using `pip`?

**Comment by belwood** [comment] 2018-03-21 12:35
pip install h5py==2.8.0rc1

**Comment by tdegeus** [comment] 2018-03-21 18:31
Great!

On a related note, why do I have to force `pip` to upgrade? `2.8.0rc1` is obviously newer than the `2.7.1`  version that I had. 

But the following did not work for me:

```bash
pip3 install --upgrade h5py
```

nor 

```bash
pip3 install --upgrade --force-reinstall h5py
``` 

nor clearing `pip`'s cache first.

**Comment by belwood** [comment] 2018-03-21 18:32
rc is "release candidate", hence not yet released and won't be the target of upgrade.
