### ISSUE TITLE
h5py==2.8.0 floats cast to python.float or numpy.float64 non-deterministically (windows)

### ISSUE THREAD

**Issue by davidnewman02** [h5py/h5py#1051] opened 2018-06-06 11:07 UTC
When reading a file using h5py==2.80, float values read from the file as a numpy.float64 do not cast correctly back to a python.float
i.e.
```
read_float = h5py.File(filename,'r')['test_group'].attrs['test_float']
cast_float = numpy.asscalar(read_float)
type(cast_float) # This returns either a python.float or a numpy.float64 at random
```
This works fine in h5py==2.7.1; although it throws a FutureWarning which seems tangentially related 
`FutureWarning: Conversion of the second argument of issubdtype from 'float' to 'np.floating' is deprecated. In future, it will be treated as 'np.float64 == np.dtype(float).type'`

To assist reproducing bugs, please include the following:
 * Operating System Windows10
*  h5py    2.8.0
*  HDF5    1.10.2
*  Python  3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)]
*  sys.platform    win32
*  sys.maxsize     9223372036854775807
*  numpy   1.14.3

**To reproduce:**
1 - Create a minimal fast5 file
```
# create_simple_fast5.py
import h5py
filename = r"C:\test.fast5"

with h5py.File(filename,'w') as fh:
    fh.create_group('test_group')
    fh['test_group'].attrs['test_float'] = 3.7
```
2 - Read it and inspect value
``` 
# test_load_h5py.py
# Read and cast resulting numpy.float64 to python.float using np.asscalar
import h5py
import numpy
filename = r"C:\test.fast5"

with h5py.File(filename,'r') as fh:
    test_out = fh['test_group'].attrs['test_float']
    np_out = numpy.asscalar(test_out)
    print(type(test_out), type(np_out)) # The type of np_out is not deterministic
```
3- Run in a loop
```
# run_loop.py
import subprocess

for i in range(100):
    subprocess.call(["python", "test_load_h5py.py"])
```
The resulting datatype after the `numpy.asscalar` conversion is non-deterministic 
```
<class 'numpy.float64'> <class 'float'>
<class 'numpy.float64'> <class 'float'>
<class 'numpy.float64'> <class 'float'>
<class 'numpy.float64'> <class 'numpy.float64'>
<class 'numpy.float64'> <class 'float'>
<class 'numpy.float64'> <class 'float'>
<class 'numpy.float64'> <class 'numpy.float64'>
etc...
```

**Comment by aragilar** [comment] 2018-06-06 11:46
I can't reproduce this on my (Linux) system. I'm also confused how this could be caused by h5py, as if `test_out` is always an instance of `np.float64`, then this could only be a problem with `np.asscalar` not converting from a numpy object to a float object. Here's a test for that:
```python
import numpy as np
print(type(np.isscalar(np.float64(3.7))) == float)
```
If that produces False sometimes, then you've hit the same bug.

**Comment by CptApature** [comment] 2018-06-06 12:21
This appears to be windows specific; I can't reproduce on Ubuntu14, Ubuntu16, CentOS 5.11 or OSX 10.11.

I've tried reproducing the bug in pure numpy as suggested above but this has no issues. I also have no issues when using h5py==2.7.1 despite using the same numpy version (1.14.3) with both so I think the problem must lie somewhere in h5py.

I've done a bit more reading and have noticed the following:
```
h5py_float = fh['test_group'].attrs['test_float']
h5py_float.item() # This is sometimes a python.float, sometimes a numpy,float64
numpy.float64(3.7).item() # This is always a python.float, never a numpy.float64
```

**Comment by aragilar** [comment] 2018-06-06 12:47
One thing you could try is dumping the memory of the output `np.float64` (see https://mail.python.org/pipermail/python-list/2016-May/709230.html for how to do this), and seeing if there's a difference in the cases where the float is correctly converted or not.

**Comment by CptApature** [comment] 2018-06-06 13:08
It seems I do get different bytes out of h5py:
```
# test_load_h5py.py
import sys
import h5py
import numpy
import ctypes
filename = r"C:\test.hdf5"

with h5py.File(filename,'r') as fh:
    h5_out = fh['test_group'].attrs['test_float']
    h5_ptr = ctypes.cast(id(h5_out), ctypes.POINTER(ctypes.c_uint8))
    if type(h5_out) != type(numpy.asscalar(h5_out)):
        print("Cast to py-float: \n", bytes([h5_ptr[i] for i in range(sys.getsizeof(h5_out))]))
    else:
        print("Cast to np-float: \n", bytes([h5_ptr[i] for i in range(sys.getsizeof(h5_out))]))
```
When run as a subprocess in a loop:
```
...
Cast to py-float:
b'\x01\x00\x00\x00\x00\x00\x00\x00\xd0\x0e\xae\xcc\xfb\x7f\x00\x00\x9a\x99\x99\x99\x99\x99\r@\x00\x00\x00\x00\x00\x00\x00\x00'
Cast to np-float:
b'\x01\x00\x00\x00\x00\x00\x00\x00\xc02\xae\xcc\xfb\x7f\x00\x00\x9a\x99\x99\x99\x99\x99\r@\x00\x00\x00\x00\x00\x00\x00\x00'
...
```
The py-float and np-float are the same each time but different to one another.

**Comment by tacaswell** [comment] 2018-06-06 13:40
My guess is someplace in the type machinery we are iterating through a dictionary and using the first one that matches.

I suspect that this bug will happen only on py3.5 and maybe py3.4 (do not remember exactly when dictionary iteration was randomized by default).  2.7 has random (but fixed) iteration order, 3.6+ has ordered dictionaries by default.

**Comment by CptApature** [comment] 2018-06-06 15:06
@tacaswell - thanks for highlighting that - sounds like the root cause.
I can confirm the problem is resolved in python3.6 on windows.

**Comment by tacaswell** [comment] 2018-06-12 17:33
I dug into this a bit, found another bug in the type lookup, but could not reproduce this on linux.

**Comment by tacaswell** [comment] 2018-06-12 19:14
@CptApature Your last snippet is is dumping the pointer to the returned object, not anything about what is inside of it.  I am quite surprised that the memory address in stable...

**Comment by tacaswell** [comment] 2018-06-29 12:57
@CptApature With h5py 2.7 what is the type of `read_float = h5py.File(filename,'r')['test_group'].attrs['test_float']`

**Comment by aragilar** [comment] 2018-07-14 11:04
I realised this is due to the fact that long double is the same as double on Windows. I suspect #1065 should be enough to fix this, but we should check what HDF5 is doing with the underlying info for long double on Windows.

**Comment by CptApature** [comment] 2018-07-16 13:32
Great - thanks for looking into this. 
If you have a built wheel/windows-dist I'm happy to do some testing pre-v2.8.1; building from source on windows looks somewhat intimidating...

**Comment by aragilar** [comment] 2018-07-16 14:48
Looking at HDF5 source code, it appears to assume that if the size of double is the same as long double, long double and double are identical (see https://bitbucket.hdfgroup.org/projects/HDFFV/repos/hdf5/browse/src/H5detect.c#1629), so skipping long double on systems where it doesn't differ from double should be fine.

**Comment by tacaswell** [comment] 2018-10-14 04:09
@aparamon Can you look into if this issue is fixed?

**Comment by aparamon** [comment] 2018-10-15 08:18
**h5py 2.8:** Reproducible for me on Python 3.5 but not on Python 3.6+, most likely due to [order-preserving dict iteration](https://mail.python.org/pipermail/python-dev/2017-December/151283.html).

**h5py 2.9-to-be:** Not reproducible.

**Comment by tacaswell** [comment] 2018-10-15 11:52
Is this a dict that should be ordered on the h5py side or on the numpy side?

**Comment by aparamon** [comment] 2018-10-16 16:12
@tacaswell I believe the problem is in https://github.com/h5py/h5py/blob/11da4d6813b7830cb6cb04478e7d017b341d064a/h5py/h5t.pyx#L251
Your commit https://github.com/h5py/h5py/pull/1065/commits/927c8510d2cf2eda38f1816cdc156e598d4103a1 fixes iteration over `available_ftypes` several lines down, but by that time it is already garbled.

**Comment by tacaswell** [comment] 2018-10-16 16:16
Ah, even though we are sorting them, they report equal and stable-sort keeps them in that order.

**Comment by takluyver** [comment] 2018-11-05 11:19
I don't properly understand what's going on here, but I found a way of getting a list of float types from numpy which should be already in order, so hopefully it avoids dictionary ordering problems. Can anyone using Windows try #1129?

**Comment by takluyver** [comment] 2018-11-05 12:02
Never mind, it seems that's not going to work because numpy's types are more complex than I thought.

I suspect that as we're getting the types from an unordered dict from numpy, this can't be fixed in h5py except by writing some special-casing code to make sure the specific type on the specific platform does the right thing.

**Comment by takluyver** [comment] 2018-11-05 13:32
Where you're checking `type(test_out)` and consistently seeing `<class 'numpy.float64'>`, it seems there are actually two different objects with the same repr: `numpy.float64` and `numpy.longdouble` will both show up as `numpy.float64` on Windows when you examine them. You can check `test_out.dtype.char` to see the difference.

Which of `longdouble` and `float64` is more correct for reading HDF5 data when they're the same size? Clearly it should be consistent, but which one should it consistently use?

**Comment by aparamon** [comment] 2018-11-05 19:39
@takluyver The same rule as `np.double` vs `np.float32`?

**Comment by aparamon** [comment] 2018-11-05 19:49
> I suspect that as we're getting the types from an unordered dict from numpy

In Python 3.7+, there is no such thing as unordered dict -- is there? This at least provides an option for users to work the problem around.

**Comment by tacaswell** [comment] 2018-11-05 23:59
Indeed, dropping py3.5 will 'fix' the problem ;)

However, this leaves h5py behavior dependent on an implementation details of numpy (the order in which they populate the dtype dictionary) which is less than great....

**Comment by takluyver** [comment] 2018-11-13 11:08
Realistically, is this going to be fixed for 2.9, or should we bump it to a later milestone? I don't think anyone has proposed a concrete way to fix this yet.

I'm confused as to how `test_float_round_tripping` can ever work on Windows. If `longdouble` and `float64` are two different numpy dtypes that map to the same HDF5 data type, why is one of them not always converted to the other when the data is written to HDF5?

**Comment by jakirkham** [comment] 2018-12-01 21:05
What if you populated an `OrderedDict` with the keys sorted in the way you expect?

**Comment by jakirkham** [comment] 2018-12-01 21:35
Maybe PR ( https://github.com/h5py/h5py/pull/1134 ) solves this?

**Comment by jakirkham** [comment] 2018-12-01 21:53
> If `longdouble` and `float64` are two different numpy dtypes that map to the same HDF5 data type, why is one of them not always converted to the other when the data is written to HDF5?

AFAIUI NumPy defines a bunch of precision types and these may map differently on various platforms and architectures (e.g. `np.int_`). However the precision types themselves are invariant across platforms. So checking those is safe.

To back this point up a bit, please see the following code.

```python
In [1]: import numpy as np                                                                                                                                   

In [2]: list(filter(lambda t: np.issubdtype(t[1], np.floating), np.typeDict.items()))                                                                        
Out[2]: 
[('half', numpy.float16),
 ('e', numpy.float16),
 (23, numpy.float16),
 ('f', numpy.float32),
 (11, numpy.float32),
 ('double', numpy.float64),
 ('d', numpy.float64),
 (12, numpy.float64),
 ('longdouble', numpy.float128),
 ('g', numpy.float128),
 (13, numpy.float128),
 ('float16', numpy.float16),
 ('Float16', numpy.float16),
 ('f2', numpy.float16),
 ('float32', numpy.float32),
 ('Float32', numpy.float32),
 ('f4', numpy.float32),
 ('float64', numpy.float64),
 ('Float64', numpy.float64),
 ('f8', numpy.float64),
 ('float128', numpy.float128),
 ('Float128', numpy.float128),
 ('f16', numpy.float128),
 ('single', numpy.float32),
 ('float_', numpy.float64),
 ('longfloat', numpy.float128),
 ('float', numpy.float64)]
```

So really only the precision types themselves matter. Also going through all the types in `np.typeDict` is not strictly necessary as there are a lot of duplicates and many of them are uninteresting for our use case.

**Comment by tacaswell** [comment] 2018-12-07 19:17
Pushed to 2.10 so we have time to consider @jakirkham 's proposed fix.

**Closed** 2019-05-06 11:15 UTC
Labels: bug
