### ISSUE TITLE
cannot pickle/unpickle from memory

### ISSUE THREAD

**Issue by nbecker** [h5py/h5py#1446] opened 2019-11-27 14:45 UTC
To assist reproducing bugs, please include the following:
 * Operating System (e.g. Windows 10, MacOS 10.11, Ubuntu 16.04.2 LTS, CentOS 7)
 * Python version (e.g. 2.7, 3.5)
 * Where Python was acquired (e.g. system Python on MacOS or Linux, Anaconda on
   Windows)
 * h5py version (e.g. 2.6)
 * HDF5 version (e.g. 1.8.17)
 * The full traceback/stack trace shown (if it appears)

`h5py.version.info` contains the needed versions, which can be displayed by
```
python -c 'import h5py; print(h5py.version.info)'
```
where `python` should be substituted for the path to python used to install
`h5py` with.

Summary of the h5py configuration
---------------------------------

h5py    2.9.0
HDF5    1.10.5
Python  3.7.5 (default, Oct 17 2019, 12:16:48) 
[GCC 9.2.1 20190827 (Red Hat 9.2.1-1)]
sys.platform    linux
sys.maxsize     9223372036854775807
numpy   1.17.4

This code is used to dump from keras
```
            with h5py.File('does not matter', driver='core',
                       backing_store=False) as h5file:
                save_model(self.model, h5file)
                h5file.flush()  # Very important! Otherwise you get all zeroes below.
                binary_data = h5file.id.get_file_image()
                d = {'args' : args,
                     'opt' : opt,
                     'model' : binary_data,
                     'h5file' : h5file,
                     }
                dump (d, open (self.dumpfilename, 'wb'), -1)
```
dumping/loading binary data 'model' works fine (but loading it is complicated/hacky).
I hoped to just dump h5file, but it won't load:
```
/usr/lib64/python3.7/site-packages/h5py/h5f.cpython-37m-x86_64-linux-gnu.so in h5py.h5f.__pyx_unpickle_FileID()

h5py/_objects.pyx in h5py._objects.ObjectID.__cinit__()

TypeError: __cinit__() takes exactly 1 positional argument (0 given)
```

**Comment by takluyver** [comment] 2019-11-29 14:07
Duplicate of #531.

We made this fail sooner (on dumping rather than loading) in h5py 2.10. For many simple cases, [h5pickle](https://github.com/Exteris/h5pickle/) can work, but your example (with an in-memory file) is probably not one of them.

**Closed** 2019-11-29 14:07 UTC
