### ISSUE TITLE
manylinux aarch64 wheels missing for h5py v3.11

### ISSUE THREAD

**Issue by t20100** [h5py/h5py#2455] opened 2024-07-10 12:25 UTC
Hi,

manylinux aarch64 wheels are available for h5py v3.10 but not v3.11.
Would it be possible to add `aarch64` wheels for v3.11 to have wheels compatible with numpy 2?

To assist reproducing bugs, please include the following:
 * Operating System: Linux
 * Python version: 3.11
 * Where Python was acquired: Tested through cibuildwheel: https://github.com/t20100/hdf5plugin/actions/runs/9872014466/job/27261206473
 * h5py version: 3.11
 * HDF5 version: 1.14.2.
 * The full traceback/stack trace shown (if it appears):

```
  Traceback (most recent call last):
    File "/project/test/test.py", line 36, in <module>
      import h5py
    File "/tmp/tmp.9ONnSUny7m/venv/lib/python3.11/site-packages/h5py/__init__.py", line 25, in <module>
      from . import _errors
    File "h5py/_errors.pyx", line 1, in init h5py._errors
  ValueError: numpy.dtype size changed, may indicate binary incompatibility. Expected 96 from C header, got 88 from PyObject
```

**Comment by neutrinoceros** [comment] 2024-07-10 13:12
Hi, thanks for reporting.
It should still be possible to compile version 3.11 on your side to get by the lack of a wheel. Is the error you reported seen with h5py 3.11 installed ?
Can you check which numpy version you have here ?

**Comment by t20100** [comment] 2024-07-10 13:53
The reported `ValueError` exception is with `h5py` v3.10 and `numpy` v2.0.0, which is expected since h5py v3.10 does not support `numpy` 2 but does not prevent installing it either.

The question is whether h5py `manylinux aarch64` are discontinued since h5py v3.11 or just missed during the last release process?

**Comment by neutrinoceros** [comment] 2024-07-10 16:54
> The reported ValueError exception is with h5py v3.10 and numpy v2.0.0, which is expected since h5py v3.10 does not support numpy 2 but does not prevent installing it either.

Thank you for clarifying. You should still be able to install h5py 3.11 as `python -m pip install 'h5py==3.11'`, which will force pip to ignore wheels from other versions and just compile this version (note that this requires HDF5 being available on your system).

> The question is whether h5py manylinux aarch64 are discontinued since h5py v3.11 or just missed during the last release process?

I didn't find anything in the recent history indicating that change but I'm also not familiar enough with h5py's release process to answer you question confidently. I assume @takluyver or @tacaswell would know this.

**Comment by takluyver** [comment] 2024-07-13 08:53
The aarch64 wheels were missed out because Travis CI stopped doing h5py builds - not that the builds were failing, they just weren't running at all. I contacted Travis support and it started working again, but that was some time later.

They should be back at the next release, either from Travis or built on Github actions (#2444). No promises, though.

**Comment by t20100** [comment] 2024-07-15 08:32
Thanks for the clarification!

**Comment by devinrsmith** [comment] 2024-07-17 17:57
Think this is dupe of https://github.com/h5py/h5py/issues/2408

**Comment by tacaswell** [comment] 2024-07-18 02:16
Agree this is a duplicate.

**Closed by tacaswell** 2024-07-18 02:16 UTC
