### ISSUE TITLE
Unable to create dataset (bad symbol table node signature)

### ISSUE THREAD

**Issue by zillionare** [h5py/h5py#2075] opened 2022-03-29 11:37 UTC
OS: ubuntu 20.04
python: 3.8
h5py versoin: 3.6

Exception:

```
Traceback (most recent call last):
  File "alpha/utils/data/securities.py", line 196, in sync
    self.store.create_dataset(day, data=secs, dtype=dtype)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/h5py/_hl/group.py", line 149, in create_dataset
    dsid = dataset.make_new_dset(group, shape, dtype, data, name, **kwds)
  File "/root/miniconda3/envs/alpha/lib/python3.8/site-packages/h5py/_hl/dataset.py", line 142, in make_new_dset
    dset_id = h5d.create(parent.id, name, tid, sid, dcpl=dcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5d.pyx", line 87, in h5py.h5d.create
ValueError: Unable to create dataset (bad symbol table node signature)
```

I'm trying to save data like this:
```
display_name   name start_date   end_date   type
000001.XSHE         平安银行   PAYH 1991-04-03 2200-01-01  stock
000001.XSHG         上证指数   SZZS 1991-07-15 2200-01-01  index
000002.XSHE          万科A    WKA 1991-01-29 2200-01-01  stock
000002.XSHG         A股指数   AGZS 1992-02-21 2200-01-01  index
000003.XSHG         B股指数   BGZS 1992-02-21 2200-01-01  index
...                  ...    ...        ...        ...    ...
603993.XSHG         洛阳钼业   LYMY 2012-10-09 2200-01-01  stock
603996.XSHG        *ST中新  *STZX 2015-12-22 2200-01-01  stock
603997.XSHG         继峰股份   JFGF 2015-03-02 2200-01-01  stock
603998.XSHG         方盛制药   FSZY 2014-12-05 2200-01-01  stock
603999.XSHG         读者传媒   DZCM 2015-12-10 2200-01-01  stock
```

the type of data to be saved is a numpy structured array with dtype:
```
                h5str = h5py.string_dtype(encoding="utf-8")
                dtype = [
                    ("code", h5str),
                    ("display_name", h5str),
                    ("name", h5str),
                    ("ipo", "<i8"),
                    ("end", "<i8"),
                    ("type", h5str),
                ]
```

all dates are converted into in beforehand.

Please suggest what happening here and if I can get a workaround

**Comment by takluyver** [comment] 2022-03-29 14:57
That error sounds like the HDF5 file you're trying to add to has got corrupted somehow, so HDF5 refuses to work with it. That's an educated guess, but if it's right, then the only thing to do is to create a new file and try to copy over any data from the old file that you want to keep.

**Comment by takluyver** [comment] 2022-04-05 13:04
Closing as it sounds like this is caused by a corrupt file, which h5py can't do anything about.

We can reopen this if there's a way to reproduce it while creating a new file. Though that would likely be a bug in HDF5 rather than h5py - h5py only touches files through HDF5 library calls.

**Closed by takluyver** 2022-04-05 13:04 UTC
