### ISSUE TITLE
Failure to handle multiple opened Files located on network drives in Windows 10

### ISSUE THREAD

**Issue by LLindenbauer** [h5py/h5py#1518] opened 2020-03-19 17:18 UTC
Dear all!

I have found an issue where having multiple files opened simultaneously (i.e., not closing them) opened from a network drive, only one of the files is actually used. I have created MWE below.

Windows 10 (64 Bit)
Python 3.7
Anaconda 2018.12

h5py.version.info
```
h5py    2.8.0
HDF5    1.10.2
Python  3.7.1 (default, Dec 10 2018, 22:54:23) [MSC v.1915 64 bit (AMD64)]
sys.platform    win32
sys.maxsize     9223372036854775807
numpy   1.15.4
```

## The minimal example

If run from a folder on a hard drive, this produces the expected result (4 files, each containing their respective group). In a network folder accessed via e.g. "\\\\Host\Folder\example", the file multi_test4.h5 will only be created the second time the h5py.File() constructor is called, but will remain at 0 bytes. The constructor instead seems to open multi_test3.h5 (although the .filename attribute tells otherwise), observed by creating a group in that file that appears inside the other opened file.

```
import h5py
# If only one file is open at a time, everything seems fine

filename1 = "multi_test1.h5"
filename2 = "multi_test2.h5"
write_f1 = h5py.File(filename1, "a")
try:
    g1 = write_f1.create_group("Group_in_File_1")
except Exception:
    pass
write_f1.close()
write_f2 = h5py.File(filename2, "a")
try:
    g2 = write_f2.create_group("Group_in_File_2")
except Exception:
    pass
write_f2.close()

# If two files are open at the same time, things break

filename3 = "multi_test3.h5"
filename4 = "multi_test4.h5"
write_f3 = h5py.File(filename3, "a")
try:
    write_f4 = h5py.File(filename4, "a")
except OSError as e:
    print(e)
    # Unable to create file (file exists)
    # This error happens only once.
    write_f4 = h5py.File(filename4, "a")
try:
    g3 = write_f3.create_group("Group_in_File_3")
except Exception:
    pass
try:
    g4 = write_f4.create_group("Group_in_File_4")
except Exception:
    pass

print(write_f4.filename)
# multi_test4.h5

write_f3.close()
write_f4.close()

read_f1 = h5py.File(filename1, "r")
print(list(read_f1))
#['Group_in_File_1']
read_f1.close()

read_f3 = h5py.File(filename3, "r")
print(list(read_f3))
#['Group_in_File_3', 'Group_in_File_4']
read_f3.close()

try:
    read_f4 = h5py.File(filename4, "r")
except OSError as e:
    print(e)
    # Unable to open file (file signature not found)

```

**Comment by LLindenbauer** [comment] 2020-03-20 08:55
I have some indication that the problem is at a lower level in the H5 libraries, as I can observe similar behaviour with the pandas DataFrame.to_hdf() function and also when using a standalone hdf viewer.

**Comment by takluyver** [comment] 2020-03-20 09:40
As you suspect it's an HDF5 problem more generally, you might want to try raising it on the [HDF forum](https://forum.hdfgroup.org/), or email help@hdgroup.org . But it's likely that the first step for them will be to reproduce it in C to be sure it's not a Python issue.

**Comment by kif** [comment] 2020-03-20 12:04
On Fri, 20 Mar 2020 02:40:15 -0700
Thomas Kluyver <notifications@github.com> wrote:

> As you suspect it's an HDF5 problem more generally, you might want to try raising it on the [HDF forum](https://forum.hdfgroup.org/), or email help@hdgroup.org . But it's likely that the first step for them will be to reproduce it in C to be sure it's not a Python issue.

The HDFgroup is willing to embrasse Python due to the size of the community ... I guess Elena will help.

**Comment by takluyver** [comment] 2020-07-31 15:56
@LLindenbauer did follow up on HDF forum: https://forum.hdfgroup.org/t/possible-bug-on-hdf5-on-windows-with-files-located-on-a-network-drive/7127

The response from HDF group does seem to suggest that this might be a known issue with HDF5. It's trying to detect when the same physical file is opened twice (even if you have e.g. two hardlinks referring to the same data on disk), but this can't reliably be done with some network filesystems.

I'm going to close this as I don't believe there's anything we can do in h5py to solve that.

**Closed by takluyver** 2020-07-31 15:56 UTC
